### ISSUE TITLE
MultiNamespacedCacheBuilder support namespace list with empty string 

### ISSUE THREAD

**Issue by morvencao** [kubernetes-sigs/controller-runtime#1006]
When I build the the cache by the `MultiNamespacedCacheBuilder` with namespace slice of empty string, then I get error in operator logs:

```
error getting IstioOperator iop: unable to get: istio-system/example-istiocontrolplane because of unknown namespace for the cache
```

Does it mean that the `MultiNamespacedCacheBuilder` doesn't support namespace list with empty string, we have to specify the namespace list other that empty string.

I thought empty string would mean that the cache will sync all namespaces.

/kind bug

**Comment by vincepri** [comment]
/priority awaiting-more-evidence

I'm not sure we have enough to debug here, if someone else is familiar with this use case, or if we can look at the code and your expected results, that might help.

**Comment by camilamacedo86** [comment]
Hi @morvencao, 

The MultiNamespacedCacheBuilder is only useful when you want to cache in the Manager a List of namespaces. If you want to use 1 or ALL then you should not use it. You can check its doc: 

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go#L37-L41

Also, to know how to use it see: https://book.kubebuilder.io/cronjob-tutorial/empty-main.html

So, if you would like to watch all you should not use this one and see that it is the default behaviour of the manager. 

Regards the error `error getting IstioOperator iop: unable to get: istio-system/example-istiocontrolplane because of unknown namespace for the cache`, you are probably trying to get a resource on this namespace and then it is telling for you that the namespace was not found since it is not cached in the manager. 

I think it can be safely closed, however, feel free to ping us if you need help with.
