### ISSUE TITLE
Envtest: filtering duplicated webhook configurations by GVK and Name

### ISSUE THREAD

**Issue by jiachengxu** [kubernetes-sigs/controller-runtime#1081]
Currently, in envtest, we don't filter duplicated webhook configurations, we should do something similar as CRD: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/crd.go#L316-L324, filtering out duplicated configurations.

**Comment by camilamacedo86** [comment]
Hi @jiachengxu, 

For webhooks shows that it will use a map where the GVK is the index. So, I think it would not have duplications, See: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/webhook.go#L211. However, I might be missing something here. So:

- Could you please describe the steps required to be performed/reproduce the issue that motivates you to make this RFE? 
- Also, if you see that it still required wdyt about to collab with the project and push a pr with your suggestion/rfe against the master? However, please do not forget to describe what issue it solves and the steps required to reproduce it. Otherwise, could you please close this one?

**Comment by jiachengxu** [comment]
Thanks @camilamacedo86, you are right, this is not an issue, I will just close this.
/close
