### ISSUE TITLE
Watching multiple namespaces for multiple resources

### ISSUE THREAD

**Issue by pkoushik** [kubernetes-sigs/controller-runtime#1127]
I'm using a controller which is watching one namespace with a custom resource, but I would like it to be able to access multiple namespaces. I'm running into an issue where even with the proper RBAC set I am unable to get core resources (e.g secrets) from a namespace I'm not watching, instead I get resource not found. 

I want to understand what is the recommended way to watch multiple namespaces and have the client in the reconciler be able to retrieve resources from multiple namespaces.

**Comment by alvaroaleman** [comment]
@pkoushik have you looked at the [MultiNamespacCache](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/cache#MultiNamespacedCacheBuilder)?

/triage support

**Comment by pkoushik** [comment]
@alvaroaleman I haven't looked into it. Wouldn't this require interaction with a cache object rather than the client found in the reconciler? Or does the client use this cache to interact with the cluster resources? When will this cache be updated?

**Comment by pjotre86** [comment]
Could you solve the problem @pkoushik ? 
I think I'm running into the same problem:
I'm trying to synch a helm deployment in a separate namespace (single cluster setup). In the kube-agent logs I find:
`error msg="error syncing 'error syncing 'cluster-fleet-local-local-1a3d67d0a899/my-gitrepo-helm': handler bundle-deploy: query: failed to query with labels: secrets is forbidden: User \"serviceaccount:fleet-system:rancher-fleet-serviceaccount\" cannot list resource \"secrets\" in API group \"\" in the namespace \"my-namespace\", requeuing`
I even granted cluster-admin permissions to the service account, it didn't help.

**Comment by camilamacedo86** [comment]
Hi @pjotre86 and @pkoushik,

Your problem is that your operator has not the permissions (RBAC) to list secrets in the cluster.  You need to update the role.yaml file to give these permissions such as is done [here](https://github.com/operator-framework/operator-sdk/blob/master/testdata/helm/memcached-operator/config/rbac/role.yaml#L84-L112) for other resources. 

I am closing this as sorted out. However, if you still needing help please raise a new issue and fill all template and in this way, provide all required information for we are able to help you with it. Indeed the snippet code of your projects which in this case shows to be the `role.yaml` file.
