### ISSUE TITLE
Webhook does not return error even when an invalid certificate has been provided

### ISSUE THREAD

**Issue by SrishT** [kubernetes-sigs/controller-runtime#1169]
Since webhooks must be served via HTTPS, they need proper certificates to be configured.
However the following command which is used to build the webhook does not return any error if an invalid certificate has been provided.
```
err = ctrl.NewWebhookManagedBy(manager.Manager).
	For(runtime.Object).
	Complete()
```

Due to this the `ValidatingAdmissionWebhook` does not reject invalid requests, which defeats the purpose of having the webhook (this ends up giving more flexibility to the end user instead of restricting him in case an invalid/expired certificate has been used, which is certainly not desirable)
We simply see the following logs in the operator when the webhook has been configured with an invalid certificate
```
TLS handshake error from 172.32.23.2:53648: remote error: tls: bad certificate
```

Could you make changes to ensure that `Complete()` returns an error in case an invalid certificate has been provided, or help me with a workaround so that we can overcome this issue?

**Comment by dsbrng25b** [comment]
> ... if an invalid certificate has been provided.

What do you consider as an invalid certificate? I think for the webhook server the certificate is valid, but either the API server does not trust the wehbook servers certificate or provides a client certificate which the webhook server does not accept.

Have you configured the appropriate CA in your ValidatingWebhookConfiguration (caBundle) or in your API server?
Do you set ClientCAName in your Webhook server (https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/server.go#L65)? If yes you have to make sure that the API server provides a certificate which is trusted by that CA.

> Due to this the ValidatingAdmissionWebhook does not reject invalid requests

If you set `failurePolicy: Fail` in the ValidatingAdmissionWebhook, requests to the webhook which fail will be rejected. But then you have to make sure that your webhook is always running, otherwise users won't be able to perform actions(create/update/delete depending on your configuration) on the appropriate resource.

**Comment by SrishT** [comment]
> Have you configured the appropriate CA in your ValidatingWebhookConfiguration (caBundle) or in your API server?
> Do you set ClientCAName in your Webhook server (https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/server.go#L65)? If yes you have to make sure that the API server provides a certificate which is trusted by that CA.
 
I have added the following annotation within the manifest for the `ValidatingWebhookConfiguration` resource
```
annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.certName }}
```
I am configuring a self-signed certificate and adding this annotation, but the kube api-server does not seem to trust this certificate because of which my operator logs are filled with these messages
```
TLS handshake error from 172.32.23.2:53648: remote error: tls: bad certificate
```
Is there a way to remedy this?

**Comment by dsbrng25b** [comment]
Is the cert-manager running without errors? Got the caBundle injected into your `ValidatingWebhookConfiguration`?
