### ISSUE TITLE
Resource corruption that comes from listing with a PageLimit

### ISSUE THREAD

**Issue by LukeWood** [kubernetes-sigs/controller-runtime#1175]
hello controller-runtime team!  I work on a team that makes heavy use of controller-runtime.

We recently experienced a resource corruption issue that we have managed to pin down to be coming from controller-runtime.

Here is a minimal reproducable version:

Note:  EnvironmentList is a k8s custom resource definition.  Environment is the same.

```
	environments := model.EnvironmentList{}
	reclaimableEnvironments = make([]model.Environment, 0)

	for until := true; until; until = environments.Continue != "" {
		if err := r.k8sClient.List(context.Background(), &environments, client.Limit(pageLimit), client.Continue(environments.Continue)); err != nil {
			logger.Error(err, "Unable to fetch environments", "err", err)
			fatal = err
			return
		}
		for _, environment := range environments.Items {
			if environment.Spec.State == model.Hibernating && !environment.Spec.Lifecycle.AutoArchive {
				reclaimableEnvironments = append(reclaimableEnvironments, environment)
			}
		}
	}
```

If you run this and exceed the page limit the values in reclaimableEnvironments are corrupted.

For example, we apply a label "environmentName" that matches the resource name.

We narrowed this down by using a debugger.

If we track a single instance at index 0 in reclaimableEnvironments during the first iteration we see something like...
```
name: some-name
labels:
    environmentName: some-name
```

Then in the second iteration of paging we see...
```
name: some-name
labels:
    environmentName: some-other-name
```

This leads me to believe that:
something in https://github.com/kubernetes-sigs/controller-runtime/blob/9f8aab6551a3ecc211b6c6078245899495b7e0f5/pkg/client/client_cache.go is overwriting the previous version. 
 I believe this because client_cache seems to perform some mutations onto pointer objects in the cached resource maps.

**Comment by DirectXMan12** [comment]
okay, so, this isn't actually a bug in any of our stuff.  It actually turns out not to even be a bug in the traditional sense, in-as-much as it is semi-surprising behavior in in `json.Decode` and the fact that data lifetime is both super important and wildly unclear in languages with references and/or pass-by-reference semantics.

So:

`client.List` calls `client-go/rest.Request.Into`, somewhat unsurprisingly, to decode the result into the object provided.  `Into` calls `Decode`, which calls the `json-iterator` equivalent of `json.Unmarshal` (but `encoding/json` exhibits the same behavior here AFAICT).

Now here comes the important part: presumably to avoid allocations, if you expect a reference value at any given point in the JSON unmarshalling process, and you already have a non-nil one, it's just used.  For instance:

```go
obj := struct{ M map[string]int }{M: map[string]int{"a": 1}}
json.Unmarshal([]byte(`{"M": {"b": 2}}`), &obj)
fmt.Printf("%v", obj)
// Output: {map[a:1 b:2]}
```

Now, this, in retrospect, is perhaps not all surprising.  It falls in line with the general behavior of the `json` package.

However, it does make for some surprising interactions, since *maps are reference types*.
Here, we make a shallow copy of each `Environment` into `reclaimableEnvironments`.  Importantly, `Environment.ObjectMeta` is a struct-value, so it's copied.  `Environment.ObjectMeta.Name` is a string (which is immutable) so `json.Unmarshal` replaces it.  `Environment.ObjectMeta.Labels`, however, is a reference, so for all `n`, `environments.Items[n].ObjectMeta.Labels` is the same object in memory as `reclaimableEnvironments[k].ObjectMeta.Labels` for some `k`.  Thus, every unmarshal of into `environments` is going to mutate `reclaimableEnvironments` on potentially all reference fields.

if you want to avoid this, either move the declaration of `environments` into the loop, or deepcopy each item as you're saving it to `reclaimableEnvironments`, or something similar.
