### ISSUE TITLE
Allow configuring a cache sync timeout

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#1219]
Currently when a cache can not be synced (for example due to misconfigured rbac) the `Controller` will just block indefinitely/until the binary gets stopped: https://github.com/kubernetes-sigs/controller-runtime/blob/5c2b42d0dfe264fe1a187dcb11f384c0d193c042/pkg/internal/controller/controller.go#L172

As an author of controllers I want to configure a timeout for this and want my `Controller` to error out if its unable to sync its caches within this timeout.

**Comment by varshaprasad96** [comment]
Hi @alvaroaleman , I would like to work on this issue. Would the implementation be to:
- Wrap [`WaitForSync`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/source/source.go#L135-L141) to pass a `Context` with a timeout so that the ctx is cancelled when [`WaitForCacheSync`](https://www.sohamkamani.com/golang/2018-06-17-golang-using-context-cancellation/) is called.
- include a `Timeout` variable in the [controller](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L42) which falls back to a default value if not set by the user.

Is this the right approach for the implementation?

**Comment by alvaroaleman** [comment]
@varshaprasad96 yes, that sounds exactly right
