### ISSUE TITLE
client.Get() requires `list` permission

### ISSUE THREAD

**Issue by rickysway** [kubernetes-sigs/controller-runtime#1220]
```
configMapName := "test-name"
existingResource := &corev1.ConfigMap{}
err := client.Get(context.TODO(), types.NamespacedName{
	Name:      configMapName,
	Namespace: resource.Namespace,
}, existingResource)
```
When trying to call client.Get() without `list` permissions results in the error:
```
Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:***:***" cannot list resource "configmaps" in API group "" in the namespace "***"
```
Why does a client.Get() require `get`, `list` and `watch` permissions instead of only just `get`?

**Comment by alvaroaleman** [comment]
@rickysway see the docs on `manager.GetClient` and `options.NewClient` in the [godocs](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options)

**Comment by dsbrng25b** [comment]
Does this error really occur during on the client.Get() call and not already during startup? Because soon as you use ctrl.NewControllerManagedBy(mgr) with For() or Owns() or a Watch() on the controller, the manager wants to list and watch this resource to get notified on changes (https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes).

**Comment by dsbrng25b** [comment]
Ok, I am probably wrong. If I understood #1222 correctly it seems that if you use Get or List on a resource for the first time it automatically gets added to the the informers which means it starts to watch that resource.

**Comment by coderanger** [comment]
Going to close this out. If the caching behavior is not desired it can be disabled either via setting the cache-skipped GVKs are using an uncached client instance.

/close
