### ISSUE TITLE
🐛 Webhooks for admission review v1 do not seem to work

### ISSUE THREAD

**Issue by Porges** [kubernetes-sigs/controller-runtime#1272]
This was mentioned before in #1015 but the support for admission review version `v1` seems to be incomplete.

It looks like the webhook does not properly copy the `uid` into the response, so any webhook calls fail with a message like `expected response.uid="e0505ce1-d1b5-4eba-8329-0398905952c0", got ""`.

See K8s documentation [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#response):

> At a minimum, the `response` stanza must contain the following fields:
>
> * `uid`, copied from the `request.uid` sent to the webhook

This is a problem because `controller-gen` will by default output `{Mutating,Validating}WebhookConfiguration`s that target both `v1` and `v1beta1`, and they will not work when k8s picks `v1`.

**Comment by prometherion** [comment]
I'm facing the same issue for my Open Source project, aiming to upgrade to `k8s.io/api/admission/v1`.

I got some thoughts on how to solve this but would be an absolutely breaking change

https://github.com/kubernetes-sigs/controller-runtime/blob/7c637a286de6aab7ae674a56d06f8a718f258ac1/pkg/webhook/admission/webhook.go#L43-L45

Right now `controller-runtime` is doing struct embedding, we could address this by leveraging an interface rather than directly accessing the struct fields that are the underlying issue, here.

If the Interface should is acceptable for maintainers, I'd like to work on this.

**Comment by Porges** [comment]
halt, bot

/remove-lifecycle stale

**Comment by serbrech** [comment]
Why is the bot closing a real bug? it's there, it's not fixed. I mean sure, mark it stale showing that no maintainer has time to look into it, but don't close it, it's hiding issues from both maintainers and users.
