### ISSUE TITLE
Import of controller-runtime calls flag for "kubeconfig"

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/controller-runtime#1396]
Hi there :-),

we are consuming `cluster-api-provider-openstack` which imports `kubernetes-sigs/controller-runtime`. 

Because [alias.go](https://github.com/kubernetes-sigs/controller-runtime/blob/master/alias.go#L23) is importing `sigs.k8s.io/controller-runtime/pkg/client/config` it always defines the ["kubeconfig" flag](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/config/config.go#L39) which then conflicts with other places where the same flag is getting defined. (e.g. inside kubernetes' e2e test framework https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L321)

Of course we are able to workaround it by not directly using the functions via `alias.go` but I think this is against the reasons why it does exist?

One alternative would be to define a `RegisterFlag` function instead of defining the flag via `func init() {...}`, however this leads to a breaking change.

<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Imprint</a>
</sup>

**Comment by chrischdi** [comment]
Addition: the same thing happens when importing `sigs.k8s.io/cluster-api-provider-openstack/api/v1alpha4`.

**Comment by johannesfrey** [comment]
FYI: I created following WIP PR: https://github.com/kubernetes-sigs/controller-runtime/pull/1999

**Comment by johannesfrey** [comment]
Should we close this issue now that #1999 has been merged? Or should we keep this issue open until the init function is removed completely (if this is desired at all)?

**Comment by sbueringer** [comment]
> Should we close this issue now that #1999 has been merged? Or should we keep this issue open until the init function is removed completely (if this is desired at all)?

Sorry for the late reply. I'm not sure if we want to drop the init function. 

Pro:
* it would be better if no flags are just implicitly registered because someone imports the config package
Con:
* nobody seems to complain about it so it seems to work for most people

On the other hand, I think almost all controller are just run inside of a Pod and barely anyone is using a --kubeconfig command line flag.

IIRC component-base/logs also dropped the implicit registering of flags. So I'm slightly in favor of getting rid of the implicit flag registration (after whatever deprecation period / release notes is appropriate)

@alvaroaleman @vincepri WDYT?
