### ISSUE TITLE
Do we have plan to support HPA of Controller

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/controller-runtime#1456]
Or we already has such functionality?

I mean `controller` support auto scaling. I understand multiple `controller` will cause conflict if every one try to handle all workspace so maybe need separate whole workspace to buckets...

**Comment by varshaprasad96** [comment]
Though it is recommended to have single controller per crd, having multiple controllers update a resource is completely acceptable (except that it may cause race conditions). Can you elaborate more on what you mean by HPA of controller, and the kind of feature/support you expecting controller-runtime to have?

**Comment by roee88** [comment]
I have the same question. 

Typically only one replica is active at a time (leader election). For scaling horizontally we need multiple replicas handling different requests (concurrently). Just disabling leader election isn't enough because it won't spread the work between replicas. The question is whether there is a recommended way to support horizontal scaling correctly and efficiently. I was thinking of bucketing based on object key using predicates or cache filters, but I don't want to reinvent the wheel.

**Comment by vincent-pli** [comment]
@roee88 
Exactly right, I hear of `knative/pkg` has some experimental and research on such topic, so I wonder to know if `ccontroller-runtime` has similar topic.

**Comment by coderanger** [comment]
We haven't really seen a case in the wild where a controller needed parallelism across multiple managers to reach usable performance. Sort of by definition the actions a controller is taking should be very fast. And we already support local concurrency (multiple worker goroutines within a single manager) via simple configuration options. Anything making so many object changes that no one node could keep up, it probably means you shouldn't be writing an operator in the first place. Maybe some day we'll find an actual use case but I think for now this is very much a "no".
