### ISSUE TITLE
Release new version (v0.9.0?) with v0.21.0 client-go support

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/controller-runtime#1473]
With v0.8.3 and v0.21.0 client-go, I get the following error

```
../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/metrics/client_go_adapter.go:135:3: cannot use &resultAdapter{...} (type *resultAdapter) as type metrics.ResultMetric in field value:
        *resultAdapter does not implement metrics.ResultMetric (wrong type for Increment method)
                have Increment(string, string, string)
                want Increment(context.Context, string, string, string)
```

This is already fixed on `master` branch, but its not ideal to deploy a version without a tag. So it would be great to release a new tag so we can pick up Kubernetes 1.21 libraries

**Comment by coderanger** [comment]
Hi there, just didn't want to leave you hanging. Right now most of the available bandwidth from the maintainer team has been going towards getting Kubebuilder 3.0 out the door, as well as prepping for some required workflow improvements now that 3.x will be supporting more versions in parallel. Once those are more stable, we'll resume the usual upgrade cycle. Going to close out this ticket since I don't think we need a specific release reminder, we'll do it as soon as we have the resources.

/close
