### ISSUE TITLE
fakeClient.List tries to populate UnstructuredList with objects of underlying type

### ISSUE THREAD

**Issue by wbrefvem** [kubernetes-sigs/controller-runtime#1511]
If I have an UnstructuredList with a known GVK, passing it to `fakeClient.List` returns an error:

```
item[0]: can't assign or convert unstructured.Unstructured into <myGV>.<myKind>
```

Running in the debugger revealed that `fakeClient.List` passes the underlying type to `client-go`, which returns a list of the underlying type. So it makes sense that fake client would error when trying to populate the `UnstructuredList` with objects it gets from `client-go`.

There should be some way for `fakeClient.List` to handle `Unstructured*` objects. IIUC the real client delegates to an unstructured client. That seems heavy-handed here, but it may be the only way to avoid a bunch of spaghetti in `fakeClient.List` just to handle `UnstructuredList` as a special case.

This is related to #702 but is not the same issue.

**Comment by alvaroaleman** [comment]
@wbrefvem I am a bit surprised this fails, we have testcases for this: https://github.com/kubernetes-sigs/controller-runtime/blob/745c7c98a7223069fcaab6b2e1b373f40d82e15a/pkg/client/fake/client_test.go#L124-L142

> Running in the debugger revealed that fakeClient.List passes the underlying type to client-go, which returns a list of the underlying type. So it makes sense that fake client would error when trying to populate the UnstructuredList with objects it gets from client-go.

We don't do that, we serialize and deserialize: https://github.com/kubernetes-sigs/controller-runtime/blob/745c7c98a7223069fcaab6b2e1b373f40d82e15a/pkg/client/fake/client.go#L333-L338

* Is your type registered in the Scheme you are using?
* Would it be possible for you to provide a small repro?

**Comment by wbrefvem** [comment]
> Is your type registered in the Scheme you are using?

Yes.

> Would it be possible for you to provide a small repro?

controller-runtime version: v0.9.0-beta.0

I'll try to be as brief as possible:

```
func (v *ValidateHandler) Handle(ctx context.Context, request admission.Request) admission.Response {
        // logic that retrieves the GVK for this type omitted
        // "service" and "serviceGVK" refer to the unkown CR type, which encapsulate configs for microservices
        // the value of labelSelector is unique to the type, e.g. for type Foo it's something like `myService==foo`
        // the key point is that the labelSelectors for the existing CR and the incoming request are identical, because the types are the same.

	unstructuredServiceList := &unstructured.UnstructuredList{}
	unstructuredServiceList.SetGroupVersionKind(serviceGVK)
	err = v.Client.List(ctx, unstructuredServiceList, &client.ListOptions{
		LabelSelector: labelSelector,
		Namespace:     v.Namespace,
	})

	if err != nil {
		log.Error(err, "error listing unstructured objects", "object GVK", serviceGVK.String())
		return admission.Errored(http.StatusInternalServerError, err)
	}

	if len(unstructuredServiceList.Items) > 0 {
		log.Info("admission of object denied because one already exists in this namespace", "GVK", serviceGVK.String(), "name", unstructuredService.GetName(), "want: 0, have: ", fmt.Sprintf("%d", (len(unstructuredServiceList.Items))))
		return admission.Denied("there is already an instance of this service deployed in this namespace")
	}

        // more stuff omitted
}
```

The test case is configured with a resource of this type already created. The expected behavior is that the call to `Client.List` should return an `UnstructuredList` with exactly 1 item, and admission should be denied. Instead, it returns the error I provided above

```

func (vts *ValidateTestSuite) SetupTest() {
        // This returns a scheme with core/v1, apps/v1, and the group that contains all CRs that this webhook validates
	testScheme, err := utils.NewSchemeWithCommonTypes()
	assert.NoError(err)
        assert.NotNil(testScheme)
	vts.Client = fake.NewFakeClientWithScheme(testScheme)
	assert.NotEmpty(vts.Client)
} 

func (vts *ValidateTestSuite) TestCustomResourceAlreadyExists() {
	assert := vts.Assert()

	err := testutils.CreateCustomResourceFromFile(vts.VNCValidateHandler.Client, "<path to manifest for my CR>")
	assert.NoError(err)

        // vts.ValidRequest is valid in the sense that everything is correct, with the exception that 
        // a resource of this type already exists, which is not reflected in the Request object itself
	response := vts.VNCValidateHandler.Handle(context.Background(), *vts.ValidRequest)
	assert.NotEmpty(response)
	assert.False(response.Allowed)
        expectErrorMessage := "there is already an instance of this service deployed in this namespace"

        // This assertion fails
        assert.Equal(expectedErrorMesssage, response.Result.Message)
} 
```

Running the test suite fails:

```
expected: "there is already an instance of this service deployed in this namespace"
actual  : "item[0]: can't assign or convert unstructured.Unstructured into <my version>.<my type>"
```

**Comment by wbrefvem** [comment]
I should also add that the GVK is generated by decoding the request into `unstructured.Unstructured` and then calling `GroupVersionKind()` on the decoded `Unstructured`.

**Comment by xunleii** [comment]
Hello, I don't know if I do something wrong or if it's another issue, but I think we can easily reach this issue using the [following example](https://replit.com/@AlexandreNICOL1/httpsgithubcomkubernetes-sigscontroller-runtime1511#main.go) :

```
package main

import (
  "fmt"
  "context"

  "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
  "sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func main() {
	c := fake.NewClientBuilder().Build()

	u := &unstructured.Unstructured{}
	u.SetAPIVersion("v1")
	u.SetKind("Namespace")
	u.SetName("default")
	_ = c.Create(context.Background(), u)

	l := &unstructured.UnstructuredList{}
	l.SetAPIVersion("v1")
	l.SetKind("NamespaceList")
	fmt.Println(c.List(context.Background(), l))
}
```

I also found that the tests seem not testing the case when tracked objects by the client are `unstructured.Unstructured`; [sigs.k8s.io/controller-runtime/pkg/client/fake/client_test.go#L124](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/fake/client_test.go#L124) only test deployments defined/created by [sigs.k8s.io/controller-runtime/pkg/client/fake/client_test.go#L835](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/fake/client_test.go#L835), which are `appsv1.Deployment`.

As far as I could go, the problem seems coming from this line : [sigs.k8s.io/controller-runtime/pkg/client/fake/client.go#L332](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/fake/client.go#L332) and more precisely [k8s.io/client-go/testing/fixture.go#L257](https://github.com/kubernetes/client-go/blob/742abf77bc608c13b86b3f5e8e890f9c813c9fc7/testing/fixture.go#L257).  
Using the `ObjectTracker` from `k8s.io/client-go/testing` call `meta.SetList`, that will try to convert the `unstructured.Unstructured` to an `appsv1.Deployment` 
- `appsv1.DeploymentList` is generated by [k8s.io/client-go/testing/fixture.go#L236](https://github.com/kubernetes/client-go/blob/742abf77bc608c13b86b3f5e8e890f9c813c9fc7/testing/fixture.go#L236)
- `appsv1.Deployment` is generated by [k8s.io/apimachinery/pkg/apis/meta/help.go#L81](https://github.com/kubernetes/apimachinery/blob/aec8116c445f5fa9d277e64ca432d978afae4ae3/pkg/api/meta/help.go#L81)
- finally, the error is throw at [k8s.io/apimachinery/pkg/apis/meta/help.go#L254](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/help.go#L254)

@wbrefvem during your tests, do you create resources using `fakeclient.Create` with `unstructured.Unstructured` objects ? (if yes, it could prove what I found)

I don't know if my thinking is correct or if I missunderstood something, but I think the issue should be fixed on `k8s.io/apimachinery/pkg/apis/meta` by checking if the `list` parameter is a `unstructured.UnstructuredList` and extracting resources from it as `unstructured.Unstructured` objects if so.

@alvaroaleman what do you think ?

**Comment by alvaroaleman** [comment]
> I also found that the tests seem not testing the case when tracked objects by the client are unstructured.Unstructured

There are, for example https://github.com/kubernetes-sigs/controller-runtime/blob/fca94d5ab22dfccc576140375042c45298ebbc4b/pkg/client/fake/client_test.go#L124 (But there are plenty more in that file)

If you can provide a fix together with a testcase that demonstonstrates the issue (i.E. doesn't pass right now) we'd be happy to take it. If you don't have a fix but a testcase, that might also help already.

k8s.io/apimachinery is part of kubernetes/kubernetes btw, so if that needs changing, you'd need to propose a patch there.

**Comment by xunleii** [comment]
Thanks for your response.

> > I also found that the tests seem not testing the case when tracked objects by the client are unstructured.Unstructured
> 
> There are, for example
> 
> https://github.com/kubernetes-sigs/controller-runtime/blob/fca94d5ab22dfccc576140375042c45298ebbc4b/pkg/client/fake/client_test.go#L124
> 
> (But there are plenty more in that file)

Sorry, I misspoke; I wanted to talk about listing unstructured objects and not listing _using_ unstructured objects.

I can provide a testcase that could demonstrates the issue: https://github.com/kubernetes-sigs/controller-runtime/compare/master...xunleii:issues/1511-no-assign-or-convert-on-unstructured, but I don't know if this test is enough.

About the fix, I will propose a patch for k8s.io/apimachinery, referencing this issue. I just want to check with you if it's a real issue or if I misuse the package.

**Comment by alvaroaleman** [comment]
> Sorry, I misspoke; I wanted to talk about listing unstructured objects and not listing using unstructured objects.

> I can provide a testcase that could demonstrates the issue: master...xunleii:issues/1511-no-assign-or-convert-on-unstructured, but I don't know if this test is enough.

So what doesn't work is listing an object that is registered in the scheme after it was created through unstructured? If yes yeah, sounds like a bug (although it is slightly questionable why you are using `unstructured.Unstructured` for an object that is registered in the scheme/whose go types you have?)

**Comment by xunleii** [comment]
Yep, that is it. 

I know, it is a bit weird to do that. I have this case for a testing library using human readable sentences (Gherkin in my case): in order to create/read/update/delete Kubernetes resources (like we do with API) in a generic way and with less code as possible, I use `unstructured.Unstructured` for all objects. _For example `When Kubernetes creates a new v1/Service 'default/test'` will create a service named `test` in the namespace `default`._

**Comment by Somefive** [comment]
Similar issue encountered as @xunleii said.
When explicitly creating an object like Deployment and then getting it through UnstructuredList is ok for the fake client.
However, if the Deployment is created through Unstructured, the retrieval will failed.

**Comment by danielfbm** [comment]
> > Sorry, I misspoke; I wanted to talk about listing unstructured objects and not listing using unstructured objects.
> 
> > I can provide a testcase that could demonstrates the issue: master...xunleii:issues/1511-no-assign-or-convert-on-unstructured, but I don't know if this test is enough.
> 
> So what doesn't work is listing an object that is registered in the scheme after it was created through unstructured? If yes yeah, sounds like a bug (although it is slightly questionable why you are using `unstructured.Unstructured` for an object that is registered in the scheme/whose go types you have?)

Its quite handy during unit tests to load a bunch of resources as `unstructured.Unstructured` using a yaml file, otherwise test case data preload becomes a lot of code 😫

**Comment by alvaroaleman** [comment]
https://github.com/kubernetes-sigs/controller-runtime/pull/1662 should fix this
