### ISSUE TITLE
Fixes for Deprecation of io/ioutil (in Go 1.16)

### ISSUE THREAD

**Issue by cndoit18** [kubernetes-sigs/controller-runtime#1518]
Please see https://golang.org/doc/go1.16#ioutil

We have a lot of references to ioutil which we need to migrate to newer package(s) mentioned in the url above:
https://cs.k8s.io/?q=io%2Fioutil&i=nope&files=.*%5C.go&excludeFiles=&repos=kubernetes-sigs/controller-runtime

We also need some verify scripts to ensure we don't add back this package

**Comment by coderanger** [comment]
I think we'll have to wait a while on this one unless we want to 100% require Go 1.16+, which seems like it's too soon to require that every operator project using controller-runtime be able to upgrade.

**Comment by cndoit18** [comment]
> I think we'll have to wait a while on this one unless we want to 100% require Go 1.16+, which seems like it's too soon to require that every operator project using controller-runtime be able to upgrade.

#1389 
our dependence has been updated, so I think it is possible

**Comment by coderanger** [comment]
controller-runtime is a library, so while this repo is built and tested with Go 1.16, I don't think we (yet) require that all library users use 1.16. I could be wrong though, I haven't tried building any of my operators with 1.15 lately :) If we already made the choice to use 1.16-only stuff then 100% yes we should do this. Otherwise we should probably ride the deprecation another few months at least to give people time to switch without cutting them off from new c-r releases.

**Comment by cndoit18** [comment]
> controller-runtime is a library, so while this repo is built and tested with Go 1.16, I don't think we (yet) require that all library users use 1.16. I could be wrong though, I haven't tried building any of my operators with 1.15 lately :) If we already made the choice to use 1.16-only stuff then 100% yes we should do this. Otherwise we should probably ride the deprecation another few months at least to give people time to switch without cutting them off from new c-r releases.

you are right. the key issue is whether we require users to use Go 1.16
