### ISSUE TITLE
How to use Own() method to get own resources

### ISSUE THREAD

**Issue by sunnoy** [kubernetes-sigs/controller-runtime#1530]
```go
       
	dep := tools.NewDeployMent(ins)
	err = controllerutil.SetOwnerReference(ins, dep, r.Scheme)
	if err != nil {
		fmt.Print("set not ok\n")
	}

// SetupWithManager sets up the controller with the Manager.
func (r *MacBookReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		// Watches(&source.Kind{Type: apiType}, &handler.EnqueueRequestForObject{})
		For(&mockv1beta1.MacBook{}).
		
		Owns(&appsv1.Deployment{}).
		Complete(r)
}
```

And how to watch deployment events ?

**Comment by Yashks1994** [comment]
Owns method you have implemented correctly.
Check the example - https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup

In order to watch the deployments events, you need to use the Watches() method to watch the events.
For eg.. 
Watches(&source.Kind{Type: &appsv1.Deployment{})
Follow this link for more abstract parameters - https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/controller.go#L126
