### ISSUE TITLE
Use of Kubectl binary in envtest setup

### ISSUE THREAD

**Issue by varshaprasad96** [kubernetes-sigs/controller-runtime#1560]
This is the issue being faced while bumping controller-runtime to 0.9.0 in [Kubebuilder declarative pattern](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern). The test involves starting an envtest environment, and using `kubectl` to create objects. [This](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/e6162cff6ff740098ff7cee89841541e4acf68f0/pkg/patterns/declarative/metrics_test.go#L243) is the test case, but to summarize the setup in short, it looks like below:

```go
	// Run local kube-apiserver & etecd
	testEnv := envtest.Environment{}
	restConf, err := testEnv.Start()
	if err != nil {
		t.Log("Maybe, you have to make sure control plane binaries" + " " +
			"(kube-apiserver, etcd & kubectl) reside in" + " " +
			"/usr/local/kubebuilder/bin" + " " +
			"or have to set environment variable" + " " +
			"KUBEBUILDER_ASSETS to the path these binaries reside in")
		t.Error(err)
	}

// set up kubectl command
      if envPath := os.Getenv("KUBEBUILDER_ASSETS"); envPath != "" {
		kubectlPath = filepath.Join(envPath, "kubectl")
	} else {
		kubectlPath = filepath.Join("/usr/local/kubebuilder/bin", "kubectl")
	}

// followed be a few other test specific setups / test cases.
....
```

When the kubectl command is run, there is an error which states that `stderr: Unable to connect to the server: x509: certificate signed by unknown authority`. It looks like `kubectl` does not trust the cluster or maybe there is something wrong in cluster setup.

Based on the recent changes in envtest which involves having authentication & authorization on by default, is there any other required change which is missing? I believed that since the built-in REST config returns an admin account, there must no other changes required to run kubectl binary (at least on permissions side). 

The reference PR which is failing: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/160

**Comment by coderanger** [comment]
Recent versions of kube-apiserver removed support for the old "insecure" port and so it is no longer available. Deeper question is why are you calling out to `kubectl` instead of using Go code? This is probably fixable but I think it would be in that test case, not in c-r. You would need to generate a full kubeconfig file using the data in the provided RESTConfig object.

**Comment by varshaprasad96** [comment]
The test case could be re written using go-client, but it would require refactoring given that there is a lot of back and forth required to change the object types from JSON to custom types defined in kb-declarative pattern. If moving to go client is not the only option, that can be done in a follow up I suppose. 

Could you elaborate more on generating a full kubeconfig file? When there is no additional user being added or changes being made to the built-in REST config, why do we need to generate the kubeconfig file again?

**Comment by coderanger** [comment]
The return value of `Start()` is a [`rest.Config`](https://pkg.go.dev/k8s.io/client-go/rest#Config) struct. You're pulling the `Host` value out of that and passing it to kubectl. That used to work because you were using the insecure port (http rather than https) so it was the only value that mattered. There is also a `CAData` field in there with the self-signed cert that you need to trust. The problem is I'm not aware of any way to pass raw CA cert data to kubectl. You need to put it in a file somewhere, either a config file or dump CAData to its own tempfile and use `--certificate-authority`.

**Comment by varshaprasad96** [comment]
Ah, got it! Thanks for the explanation @coderanger !
@atoato88 helped in fixing the issue in kb-declarative-pattern PR. Since its fixed, I'm closing the issue.
