### ISSUE TITLE
Introduce a dynamic multi-namespace cache

### ISSUE THREAD

**Issue by jmrodri** [kubernetes-sigs/controller-runtime#1590]
The DynamicMultinamespacedCache will dynamically create a cache for a given namespace on demand. Like the MultinamespacedCache, it supports cluster and namespaced resources. It also able to handle permissions granted after starting the cache, being able to create more caches on demand hence the dynamic nature. The DynamicMultinamespacedCache uses the MultinamespacedCache underneath.

Update:
We have operators that are moving from namespace scoped to cluster scoped. An operator uses caches for dependent resources, these caches are usually spun up with list/watchers for those resources using controller-runtime pattern at startup. 

If the operator is started with access only to the owned CRDs to start and not given all of the required permissions at startup. The caches will not have the dependent resources and when the admin grants permissions later the caches will not be able to react to the change.

The operator would need access to a cache that can handle dynamically changing permissions.

**Comment by joelanford** [comment]
I think there may be _some_ overlap with https://github.com/kubernetes-sigs/controller-runtime/pull/1192

In the scenario where a DynamicMultinamespaceCache is used to watch secondary objects in a namespace based on the presence of a primary object in that namespace, it would be useful for the DynamicMultinamespaceCache to be able to stop caches and free memory in namespaces it detects no longer need to be watched because a primary object is no longer present in that namespace.

**Comment by alvaroaleman** [comment]
> We have operators that are moving from namespace scoped to cluster scoped. An operator uses caches for dependent resources, these caches are usually spun up with list/watchers for those resources using controller-runtime pattern at startup.

> If the operator is started with access only to the owned CRDs to start and not given all of the required permissions at startup. The caches will not have the dependent resources and when the admin grants permissions later the caches will not be able to react to the change.

Can you give a concrete example on how someone would make use of this, i.E. how does the controller get to know about the additional namespace(s)? Also, if you want to dynamically add caches at runtime, you would also need to be able to remove them or not, otherwise this ends up being a very confusing UX for controller authors?

What keeps you from simply restarting the controller when changing its config instead?


Also, I don't understand how the gvkCache in your PR relates to this. Can we have a dedicated issue/PR for that one?

**Comment by jmrodri** [comment]
Closing this issue in favor of issue #1652
