### ISSUE TITLE
Util function to validate if a resource is owned by a particular Owner Reference

### ISSUE THREAD

**Issue by sujil02** [kubernetes-sigs/controller-runtime#1619]
Add a util function to controller runtime to validate if a certain resource is owned by a particular Owner Reference.

Reference to such a util function currently supported by [operator-utils ](https://github.com/redhat-cop/operator-utils) is found here [Owner.go](https://github.com/redhat-cop/operator-utils/blob/master/pkg/util/owner.go)

**Comment by coderanger** [comment]
Is there a particular use case for this?

**Comment by jmrodri** [comment]
@coderanger there are a few utility libraries that were created for use by operators that also use controller-runtime, some of the methods were added because they didn't already exist in controller-runtime. What @sujil02 has here is one of the utility methods that makes it easy to see if a resource is owned by a specific owner.

**Comment by coderanger** [comment]
Yes could you please explain one or more of the use cases for this method?

**Comment by joelanford** [comment]
If the use case is something along the lines of checking to see if an existing owner ref is already set so that a decision can be made to set it or not, that's already covered by the idempotent [`controllerutil.SetControllerReference()`](https://github.com/kubernetes-sigs/controller-runtime/blob/c0a5babc6854d42ab37eb5323ff024eb0dc24b9d/pkg/controller/controllerutil/controllerutil.go#L59) and [`controllerutil.SetOwnerReference()`](https://github.com/kubernetes-sigs/controller-runtime/blob/c0a5babc6854d42ab37eb5323ff024eb0dc24b9d/pkg/controller/controllerutil/controllerutil.go#L96) functions.

**Comment by varshaprasad96** [comment]
+1, the logic of finding if an owner ref is set as specified in [issue](https://github.com/redhat-cop/operator-utils/blob/26a9d4efe6c40ed22f302342196ea6afc8b63170/pkg/util/owner.go#L24-L35), is what is present [here](https://github.com/kubernetes-sigs/controller-runtime/blob/c0a5babc6854d42ab37eb5323ff024eb0dc24b9d/pkg/controller/controllerutil/controllerutil.go#L125-L141). But just curious, is there any other use case of finding owner ref?
