### ISSUE TITLE
Insufficient RBAC permissions results only in cache timeout reported

### ISSUE THREAD

**Issue by zaneb** [kubernetes-sigs/controller-runtime#1653]
With controller-runtime v0.9.0, attempting to watch a resource type for which we do not have RBAC watch permissions results in an error after a couple of minutes like:

```
Could not wait for Cache to sync
failed to wait for <controller> caches to sync: no matches for kind "<Kind>" in version "<Group>/<Version>"
```

For debugging it would be helpful to log an error (as controller-runtime already does e.g. when the CRD is missing altogether) stating that the problem is lack of permissions as soon as that error is experienced.

**Comment by alvaroaleman** [comment]
This would be great, the issue is that the underlying informers from client-go we use do not report this info. They only provide a boolean telling you if they were successful in syncing or not, no error.

The call chain is approximately:
Source: https://github.com/kubernetes-sigs/controller-runtime/blob/0a9a7778cdb6d4cca3a3b9f268d90a85aa6f5fdf/pkg/source/source.go#L135
Cache: https://github.com/kubernetes-sigs/controller-runtime/blob/0a9a7778cdb6d4cca3a3b9f268d90a85aa6f5fdf/pkg/cache/internal/informers_map.go#L201
SharedInformer: https://github.com/kubernetes/client-go/blob/a31b18a6ac98bbff0dd1055707dfde1b0a98ff68/tools/cache/shared_informer.go#L163

**Comment by ysong6** [comment]
@zaneb How did you know it's because insufficient RBAC permissions. I meet the same issue now. I thought it might not be caused for insufficient RBAC permissions, for the same code can run in the laptop. Could you please give me some hint for troubleshooting? Thank you.

**Comment by zaneb** [comment]
@ysong6 I don't recall much detail. I checked my notes and it looks like I just had a lucky guess after staring at it for a long time, which I then verified by installing the correct RBAC permissions and seeing that it now worked.
