### ISSUE TITLE
export queue's length of Controller

### ISSUE THREAD

**Issue by zouyee** [kubernetes-sigs/controller-runtime#1733]
Describe the feature request

In `istio`, we are using `kubebuilder` reconcile to process crd object(like serviceentry) in the Kubernetes and store them in the cache. Every time we start the `polit-discovery` componet, it will rebuild the cache which we want to know when the cache is complete. If the events are stacked in the queue, the cache is incomplete and our service is unreliable. We need a method which can tell us all the pods are scanned once to guarantee that we get a full cache.

Describe alternatives you've considered

Our idea is to expose the length of the queue. If the queue is empty, we can consider that all the events have been processed.

**Comment by coderanger** [comment]
-1 on this approach, it's going to get all kinds of complicated because new events will still be coming in. There may never be a point at which the queue is empty. Is there a reason you can't use the field indexer system and normal List/Get? If you want to avoid that, I'm not sure there's a good way to handle this, other than making an explicit snapshot via List and then in Reconcile check if you've seen all those objects. That is still very susceptible to race conditions though.

**Comment by FillZpp** [comment]
1. As @coderanger said, empty queue does not mean there are no incoming events or objects.
2. Even if the length of queue is `0`, it just indicates the length of the **waiting queue**. But the **dirty set** or **delaying queue** might not be empty, so it does not mean there are no objects waiting for reconciling.
3. I don't think it is a good idea to define a *complete state*, for the world of Kubernetes is dynamic. You can use `HasSynced()` to wait for all existing objects been synced into cache, but there is no way to wait for controllers completed reconciling, because objects may be changed and events may be triggered any time.

**Comment by coderanger** [comment]
Also the workqueue is kind of an implementation detail. It's been useful but I could easily imagine a world where we switch to something else for some reason where there is no longer a meaningful "length" (on top of FillZpp's point that even now stuff can be in more states than just "pending").
