### ISSUE TITLE
Is there a way to create a fixed size cache?

### ISSUE THREAD

**Issue by gallettilance** [kubernetes-sigs/controller-runtime#1742]
I know you can do pagination for `List()` calls - can something similar be done for the cache in order to prevent memory exhaustion when watching resources like secrets, rolebindings, etc. that may be numerous on a large multi-tenant cluster.

**Comment by coderanger** [comment]
Not currently, but you can do partial or no caching to reduce the size of the cache. We also support metadata only watches.

**Comment by gallettilance** [comment]
@coderanger thanks for the quick answer! Do you have links to partial caching? Are you referring to `ClientDisableCacheFor`, or using `Label` and `Field` selectors when creating the cache, or something else?

**Comment by coderanger** [comment]
DisableFor would be to remove caching of a particular type, for example if you need to watch it for event triggers but don't need the actual content (or are okay with uncached gets). For partial stuff, you can pass in a selector to restrict the watch, which also restricts the cache since it is driven from the watch. I think there is a PR somewhere to do a normal watch with selector-based caching but I don't remember where I saw that.
