### ISSUE TITLE
Deletion verb interrupted by mutating handler

### ISSUE THREAD

**Issue by AnyISalIn** [kubernetes-sigs/controller-runtime#1762]
### Environment

* kubebuilder v3.1.0
* controller-runtime v0.8.3
* kubernetes 1.20.3

### How to reproduce

* enable deletion validation for CRD
* enable mutating handler for CRD
* execute `kubectl delete <crd> <cr>`, its should returns `Error from server: admission webhook "xxxxxx" denied the request: there is no content to decode`

### Possible  Problems

when you want to delete a CR, [mutaing handler](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/admission/defaulter.go#L61) want to `Decode(req.Object)`, however it doesn't work, cause Kubernetes DELETE Admission Request Body only contains `OldObject`  and the deletion verb is broken.

can we skip deletion verb in the mutating handler?

### Reference Issues

https://github.com/kubernetes-sigs/controller-runtime/issues/1278

**Comment by FillZpp** [comment]
Yeah, it used to be in `req.Object` and has been moved to `req.OldObject` since Kubernetes 1.16 for both validating and mutating DELETE.

I'm not sure should we just skip for deletion request [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/admission/defaulter.go#L61), or improve it like this:

```
	reqObj := req.Object
	if req.Operation == admissionv1.Delete {
		reqObj = req.OldObject
	}
	if err := h.decoder.DecodeRaw(reqObj, obj); err != nil {
		return Errored(http.StatusBadRequest, err)
	}
```

I prefer the latter one, for it is a little weird if users enabled DELETE mutation and got nothing when objects deleted.

**Comment by AnyISalIn** [comment]
@FillZpp Thanks! but I don't know what happens when mutations return some diff patches when sending DELETE verb?

**Comment by FillZpp** [comment]
> @FillZpp Thanks! but I don't know what happens when mutations return some diff patches when sending DELETE verb?

That's the problem. Could you run a test for the scenario? Or I can do this when I'm free in the new year :)

**Comment by AnyISalIn** [comment]
> > @FillZpp Thanks! but I don't know what happens when mutations return some diff patches when sending DELETE verb?
> 
> That's the problem. Could you run a test for the scenario? Or I can do this when I'm free in the new year :)

Okay, I will try later, Happy New Year.

**Comment by AnyISalIn** [comment]
@FillZpp Kubernetes seems unable to handle patches on DELETE Verb when mutation handler, see from here [mutating/dispatcher.go#L315](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go#L315), may we need to skip it? 

```
Error from server (InternalError): Internal error occurred: admission webhook "mmutatingtest.kb.io" attempted to modify the object, which is not supported for this operation
```

**Comment by FillZpp** [comment]
> Kubernetes seems unable to handle patches on DELETE verb in mutation handler, see from here mutating/dispatcher.go#L315

Alright, if so, I think it is reasonable to skip this verb.

What's more, I'm not sure if we should disable [the DELETE verb in controller-tools](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L148) so that it will not generate it in MutatingWebhookConfiguration or return an error to warn users that DELETE can not be used in mutating webhook?

Any suggestions? @alvaroaleman @vincepri

**Comment by alvaroaleman** [comment]
The fix was merged, why are we keeping this open?

**Comment by FillZpp** [comment]
> The fix was merged, why are we keeping this open?

Oh sorry, my mistake.

/close
