### ISSUE TITLE
Manager error results in pod crash

### ISSUE THREAD

**Issue by delps1001** [kubernetes-sigs/controller-runtime#1774]
Using the manager, if there is an issue with leader election, our program should exit immediately according to the docs:

https://github.com/kubernetes-sigs/controller-runtime/blob/b8db76e66383819c94f530bd4b8dea60025b716f/pkg/manager/manager.go#L81-L87

However, when I experience a network issue in our kubernetes cluster, sometimes our application pod will continually restart because it has momentarily lost connection to the kubernetes api (again, due to some intermittent connection issues). This happens because when the pod tries to acquire/reacquire the leader lock, it times out when the pod starts back up, then exits, rinse and repeat.

I'm seeing logs like this:

```
E0108 19:06:53.325550 1 leaderelection.go:361] Failed to update lock: Put "https://1.1.1.1:443/apis/coordination.k8s.io/v1/namespaces/namespace/leases/my-lock": context deadline exceeded
[application will fatally exit]
...
E0108 19:15:09.629250 1 leaderelection.go:325] error retrieving resource lock my-namespace/my-lock: Get "https://1.1.1.1:443/api/v1/namespaces/namespace/configmaps/my-lock": context deadline exceeded
[application will fatally exit]
```

Is this expected behavior? Is there anything I can do to prevent the pods from restarting continually when there are connectivity issues to the kubernetes apis?

**Comment by FillZpp** [comment]
> Is this expected behavior?

Yes, it is the expected behavior. The client doesn't know whether the network issue is in the whole cluster or itself. If it continues to run without restart and another manager pod has been new leader, they might work at the same time and lead to unexpected result.

> Is there anything I can do to prevent the pods from restarting continually when there are connectivity issues to the kubernetes apis?

1. You can deploy your controller with one replica, so that you can disable the leader election. But this is not the recommended way.
2. You can change the lease and renew duration of leader election, which are options provided in `manager.Options`. For example, you can set `LeaseDuration=60s` and `RenewDeadline=55s`, so that it can tolerate network issue for 60s, in which time it will keep retry calling every 2s (RetryPeriod). By default it can only wait for 15s and then stop itself.

https://github.com/kubernetes-sigs/controller-runtime/blob/19f9afeed131dfa3e215723a97520433c10946cc/pkg/manager/manager.go#L178-L187

**Comment by delps1001** [comment]
@FillZpp thank you for the information!

**Comment by shaharr-ma** [comment]
> > Is this expected behavior?
> 
> Yes, it is the expected behavior. The client doesn't know whether the network issue is in the whole cluster or itself. If it continues to run without restart and another manager pod has been new leader, they might work at the same time and lead to unexpected result.
> 
> > Is there anything I can do to prevent the pods from restarting continually when there are connectivity issues to the kubernetes apis?
> 
> 1. You can deploy your controller with one replica, so that you can disable the leader election. But this is not the recommended way.
> 2. You can change the lease and renew duration of leader election, which are options provided in `manager.Options`. For example, you can set `LeaseDuration=60s` and `RenewDeadline=55s`, so that it can tolerate network issue for 60s, in which time it will keep retry calling every 2s (RetryPeriod). By default it can only wait for 15s and then stop itself.
> 
> https://github.com/kubernetes-sigs/controller-runtime/blob/19f9afeed131dfa3e215723a97520433c10946cc/pkg/manager/manager.go#L178-L187

Hi, does it possible to expose those values as HELM variables ?
