### ISSUE TITLE
Error handling in MapFunc

### ISSUE THREAD

**Issue by LiuShuaiyi** [kubernetes-sigs/controller-runtime#1923]
Hello!

I want to ask about the best practice for doing error handling in MapFunc: https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.12.1/pkg/handler#MapFunc

Since MapFunc doesn't return any error, most implementations of MapFunc I've seen just log the error and return nil. (e.g. https://sourcegraph.com/github.com/kubernetes-sigs/cluster-api-provider-azure/-/blob/exp/controllers/helpers.go?L531)
I am a little concerned with this. If there is a transient error in the MapFunc, wouldn't it cause the controller to miss some reconciliation loops?

**Comment by FillZpp** [comment]
@LiuShuaiyi  It is because `MapFunc` only let ppl to decide which requests should be put into the workqueue based on the given object. It does not care those internal errors in the custom function.

- For `enqueueRequestsFromMapFunc`, even if it get errors returned from `MapFunc`, it can do nothing but a warning log.
- For users that are going to implement the `MapFunc`, they just have to tell controller-runtime which requests should be enqueued and reconciled. So if it might get some internal errors, it has to decide whether the requests should be reconciled or not according to the error cases.
