### ISSUE TITLE
Pagination does not work when using manager client 

### ISSUE THREAD

**Issue by gmonz36** [kubernetes-sigs/controller-runtime#1960]
I am trying to paginate the results when listing all the pods in a cluster, and I discovered 2 different results when using clients initialized in a different way.

When using the controller-runtime client package `New` function, I can successfully paginate the results:
```
listClient, err := client.New(ctrl.GetConfigOrDie(), client.Options{})
if err != nil {
	logger.Error(err, "unable to create client")
	os.Exit(1)
}

limit := 1
podList := &corev1.PodList{}
opts := &client.ListOptions{
	Raw:   nil,
	Limit: int64(limit),
}

if err := listClient.List(ctx, podList, opts); err != nil {
	log.Error(err, "failed to list pods")
	os.Exit(1)
if podList.Continue != "" {
	log.WithValues("RemainingItemCount", *podList.RemainingItemCount).Info("Retrieving next page of pods")
	opts.Continue = podList.Continue
}
```
but when I try to use a client obtained with the controller-runtime `NewManager` function, the limit is applied, but the `ListMeta` field of the pod list is always empty after calling the `List` function. I would have expected that the `ListMeta` would include a `Continue` and `RemainingItemCount` like the code above.
```
import (
	ctrl "sigs.k8s.io/controller-runtime"
)
mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{})
if err != nil {
	log.Error(err, "unable to start manager")
	os.Exit(1)
}

listClient := mgr.GetClient()

limit := 1
podList := &corev1.PodList{}
opts := &client.ListOptions{
	Raw:   nil,
	Limit: int64(limit),
}

if err := listClient.List(ctx, podList, opts); err != nil {
	log.Error(err, "failed to list pods")
	os.Exit(1)
if podList.Continue != "" {
	log.WithValues("RemainingItemCount", *podList.RemainingItemCount).Info("Retrieving next page of pods")
	opts.Continue = podList.Continue
}
```
I am wondering why in this case the limit would be applied but I would not receive a `Continue` string. Is this because the manager client uses the cache for reads?

**Comment by FillZpp** [comment]
>  Is this because the manager client uses the cache for reads?

Yeah.

- When you `New()` a client from `sigs.k8s.io/controller-runtime/pkg/client`, it creates an APIServer client that do both read and write requests to APIServer.
- When you `GetClient()` from Manager, it returns a delegating client ([here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/split.go#L69)), see the doc:

https://github.com/kubernetes-sigs/controller-runtime/blob/f0351217e9e026533aece74d054b23cae5441659/pkg/client/split.go#L39-L43

Solutions:

- You can `GetAPIReader()` from Manager, that's a reader that do read requests to APIServer.
- If you expect some GVKs that should always get from APIServer instead of cache, you can put the object in [this option](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L267)

**Comment by gmonz36** [comment]
Thank you for the explanation and solutions. Using `GetAPIReader()` is working with my use case.
