### ISSUE TITLE
How long is cache valid?

### ISSUE THREAD

**Issue by Noksa** [kubernetes-sigs/controller-runtime#1993]
Hello guys!

First of all, thanks for the such great library!

Probably, I have a stupid question, but I would so appreciate if you answer!

Thanks!

A small example:
```
	pod := v1.Pod{}
	err = r.Get(ctx, req.NamespacedName, &pod)
	if err != nil {
		logger.Info("Pod was deleted, no action required anymore, removing it from queue.")
		return ctrl.Result{}, nil
	}
	logger.Info("Annotation value: %v", pod.Annotations["test"])
	_, err = controllerutil.CreateOrPatch(ctx, r, &pod, func() error {
			pod.Annotations["test"] = "test"
			return nil
	})
	if err != nil {
			return ctrl.Result{}, err
	}
	return ctrl.Result{RequeueAfter: time.Millisecond * 1}, nil 
```

In this case, the second loop will also print empty string instead of `test`, because pod has been cached after first loop.

So my question is - how long does cache last? How much time should I wait before changes are visible in next loop?

Thanks!

PS: I know that I can use `GetApiReader` if I want to get the actual state from k8s api instead of cache, but I just want to know how long cache lasts.

**Comment by joelanford** [comment]
The time it takes for the cache to be updated depends on how long it takes the informer that populates the cache to receive the watch event from the apiserver that contains the update.

You're running into this problem because you're requeuing after 1ms. The correct way to handle this situation is to configure a watch for pods when you setup the controller with the manager, and let that watch drive reconcile requests rather than a timer.

**Comment by juliev0** [comment]
I'm trying to understand why the call to write to K8S API doesn't itself update the cache, so that Controllers don't need to worry about this sort of race condition (and also is there a way for me to write to it if I want to?)

**Comment by sbueringer** [comment]
The problem is that reading from the cache and writing to the server are two absolutely independent things.

The "cache" is managed by an informer (it uses list & watch to store objects in local storage). Write just directly goes to the apiserver.

It would be tricky to try to update the local storage in a safe way after write calls (also not sure if the underlying storage that is used by the informer is accessible)
