### ISSUE TITLE
Errors using HTTPS scheme in livenessProbe and readinessProbe

### ISSUE THREAD

**Issue by revit13** [kubernetes-sigs/controller-runtime#2283]
I get the following error when adding HTTPS scheme to livenessProbe and readinessProbe.
I have these [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/cmd/main.go#L134-L142)  `AddHealthzCheck` and `AddReadyzCheck` calls in the code which calls to [this AddHealthzCheck implementation](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/manager/manager.go#L74-L78).
How can I make the controller configured with https? 

```
Warning  Unhealthy    4m24s (x21 over 8m34s)  kubelet            Readiness probe failed: Get "https://10.244.1.10:8088/readyz": http: server gave HTTP response to HTTPS client

**Comment by vincepri** [comment]
Looks like your server is not configured with TLS options, while the client is requiring it; you'll have to set the Webhook options with a custom TLS configuration

**Comment by roytman** [comment]
Hi, @vincepri. Thank you for your response. Due to customer requirements, we do not always use a WebHook server.  However, when it is used, it runs over TLS as expected. 
We are currently experiencing an issue with the health and liveness probes. 

The manager creates the `healthProbeListener`, which is actually the [defaultHealthProbeListener](https://github.com/kubernetes-sigs/controller-runtime/blob/dca0be70fd22d5200f37d986ec83450a80295e59/pkg/manager/manager.go#L633). The createion is done according to definition in [HealthProbeBindAddress](https://github.com/kubernetes-sigs/controller-runtime/blob/dca0be70fd22d5200f37d986ec83450a80295e59/pkg/manager/manager.go#L266).
Then the `controllerManager` starts serving readiness and liveness requests with `httpServe` method. ([serveHealthProbes](https://github.com/kubernetes-sigs/controller-runtime/blob/dca0be70fd22d5200f37d986ec83450a80295e59/pkg/manager/internal.go#L315)).

I am unable to find an option to run the probes server over TLS. Am I missing something?

Running readiness or liveness checks without encryption does not necessarily create vulnerabilities, but it triggers security alerts of a penetration test.

Can you suggest something or confirm that we're not missing anything?

**Comment by sbueringer** [comment]
I think you're right and there is no way to currently do it. CR always serves the probes with http.

**Comment by troy0820** [comment]
/kind support 

Being that CR serves with http, can we close this? @revit13

**Comment by sbueringer** [comment]
Let's close this for now. Feel free to reopen, but it would be good to have a concrete use case why https is required for the readiness & liveness probes

/close
