### ISSUE TITLE
Milestones and calendar

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/controller-runtime#231]
Is it planned to manage this project using github milestones and to have a calendar about next releases (every month, 3months, ...) ? When is the release `v0.1.8` scheduled ? Where do we manage the release note of a release ?

**Comment by DirectXMan12** [comment]
I've been trying to write up how we do the release process in `VERSIONING.md`.  Let me know if that doesn't answer your questions.

/kind question
/kind versioning

**Comment by DirectXMan12** [comment]
Specifically:

> Minor and patch releases are generally done immediately after a feature or bugfix is landed, or sometimes a series of features tied together.

> Major releases are done once a sufficient amount of breaking changes are accrued. Since we don't intend to have a ton of these, the maintainers will evaluate when to do a major release as it comes up.

**Comment by hasbro17** [comment]
@DirectXMan12 Thanks for adding the versioning doc.
Right now it seems we're going to generate the release notes or CHANGELOG when making the release.
> Generate release notes using the release note tooling (TODO)
https://github.com/kubernetes-sigs/controller-runtime/blob/master/VERSIONING.md#exact-steps

I imagine you're planning to have the tool generate the notes based on the PR annotations 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/VERSIONING.md#pr-process

We'll probably still need a manual summary for `v0.1.8` since none of the PRs have those annotations:
https://github.com/kubernetes-sigs/controller-runtime/compare/v0.1.7...master

Also not sure if the `RELEASE.md` file is up to date or should be replaced by `VERSIONING.md`.
> An issue is proposing a new release with a changelog since the last release
https://github.com/kubernetes-sigs/controller-runtime/blob/master/RELEASE.md

**Comment by DirectXMan12** [comment]
> Also not sure if the `RELEASE.md` file is up to date or should be replaced by `VERSIONING.md`.

Whoops, yeah, I missed updating RELEASE.md.  That should just be retired in favor of VERSIONING.md.

> We'll probably still need a manual summary for `v0.1.8`

Yeah, we'll need some manual work for v0.1.8.

**Comment by DirectXMan12** [comment]
closing as per the current state of versioning.md
