### ISSUE TITLE
While deploying the Controller getting Error 139

### ISSUE THREAD

**Issue by ManasGupta12** [kubernetes-sigs/controller-runtime#2366]
[Dockerfile.txt](https://github.com/kubernetes-sigs/controller-runtime/files/11612069/Dockerfile.txt)
We have built an admission controller using Kubebuilder .
We are intending to add oc binary in our Docker file as our controller needs to do some oc operation (like retrieving pod ,cr details).
PFA Docker file for your reference .
So after deployment of our Admission Controller we are getting below error while scaling up the pod .
And surprisingly we are not getting any type of logs to get more details on it .
Please let me know for any suggestions .
![image](https://github.com/kubernetes-sigs/controller-runtime/assets/39985462/2905c52f-dae9-4835-b325-a5fac2f80777)

**Comment by alvaroaleman** [comment]
Please re-post your question to our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/triage support
/close
