### ISSUE TITLE
Unable to still using Component Config besides it be deprecated only

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-runtime#2370]
We are facing a hard time to bump Controller-Runtime 0.15.0 due the breaking changes.
We noticed that the ComponentConfig was deprecated. https://github.com/kubernetes-sigs/controller-runtime/issues/895

However, it seems that it also has a bug.  This means when ctrl.File is called in cmd/main.go it calls in [here](https://github.com/kubernetes-sigs/controller-runtime/pull/2149/files?diff=split&w=0#diff-dea7619d77571db36240f1b5aeb6afa4a9cb507a42dc0077dc7e96f027fd8b59R104) which registers the ComponentConfig with the scheme. Though the field has been deprecated, the ComponentConfig type should still be registered with controller-runtime.sigs.k8s.io/v1alpha1 scheme, which seems missing.

**Comment by alvaroaleman** [comment]
Sorry, I don't understand the bug. Could you provide a sample snippet of what you are trying to do?

**Comment by troy0820** [comment]
/kind support 

Is this issue fixed with the above pull request to guacamole-operator? @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @alvaroaleman,

The ComponentConfig was deprecated; therefore, it should still work fine until being removed and no longer supported.
However, that is not the case. 

Anyway, I think that can be closed and it was not very used because we did not face complains from Kubebuilder users and we already have been communicating that soon we will do a MAJOR release where this option will be removed from there.

**Comment by FengJi2021** [comment]
Run into this issue when bump controller-runtime to 0.16.x and apimachinery to compatible version.
I think many developers create their own custom ProjectConfig and extend the ControllerManagerConfigurationSpec. When user read config data with .OfKind(&ProjectConfig{}), it will workaround this error.
So the impact of this error is limited due to the use pattern of ProjectConfig.
Looking forward, the issue will be how much effort it takes to replace this deprecated feature. Discussion on going [here ](https://github.com/kubernetes-sigs/controller-runtime/issues/895)
