### ISSUE TITLE
Enable filtered list watches as watches

### ISSUE THREAD

**Issue by nkvoll** [kubernetes-sigs/controller-runtime#244]
When setting up watches during initialization it's currently not possible to filter by any selectors (which is possible using list watches).
    
For example it is not possible to only watch pods with specific labels (e.g having the label `pod-type: my-controller-type`). The current behavior results in very broad caching, which might not be desirable for large Kubernetes deployments.

In some scenarios an operator could contain multiple controllers, and they all share caches, so keying caches on GVK's alone might be problematic if they want to watch the same resource type, but with different filters.

When doing `List`/`Get`, how would one decide which of the caches to use? It seems that perhaps this needs to be an explicit choice by the operator developers?

**Comment by jeefy** [comment]
+1

I've run into a similar issue with a controller I'm writing. I wound up starting a goroutine when the controller gets added to watch/act on certain objects that are created and labeled by another controller outside of mine.

**Comment by DirectXMan12** [comment]
we'd have to specify this at the manager level, but it should be possible to pass restricting items.

**Comment by DirectXMan12** [comment]
(since caches are shared)

**Comment by DirectXMan12** [comment]
we could also let users manually specify auxiliary caches

**Comment by DirectXMan12** [comment]
if anyone has ideas for a design doc, I'd love to see them.

**Comment by DirectXMan12** [comment]
/kind feature
/priority important-soon

this has been coming up a lot lately, and seems like a good thing to tackle in the list of related issues.

**Comment by DirectXMan12** [comment]
i.e. one sketch:

Have a list-options watch predicate, smartly detect the presence of that (in some generic way) and pass it down to `GetInformer`.  If we already have a global informer, just use that.  If we don't have a global informer, create a new filtered informer.  We delay creation of informers to figure out if one person needs a global informer, and just use that, to allow splitting and combining seamlessly.  The question is how to deal with the cached client:

- :x:  cached client always tries for a global informer (seems like a performance footgun)
- :x: only one filtered informer max (breaks multi-controller managers)
- :x: cache client refuses to use global informer if filtered informers exist and a global informer does not (breaks multi-controller informers)
- :ok:  keep track of which controller a given client belongs to and which watches that client set up, and try to scope those gets to the informer it belongs to, in the case of filtered informers (complicated, serious internal refactors)
- :ok: allow users to turn off auto-caching, make them explicitly get filtered caching clients if they want (doable, more work for users).  This potentially lets us allow users to specify that they don't want the client to *ever* cache a particular object (could encourage wrong patterns).

That last one might solve multiple problems in one fell swoop, but I'd need to see a design sketch to make sure that it's not too arcane.

**Comment by pickledrick** [comment]
I will follow this to understand how this is properly implemented and any questions from a user or testing perspective please ask and I'll do my best to assist. In the interim I've implemented this for my own use case.

`	kvp := &keyValuePair{
		key:   "app",
		value: "test",
	}

	filter := newFilter(keyValueFilter(kvp))

	err = c.Watch(&source.Kind{Type: &v1.Deployment{}}, &handler.EnqueueRequestForObject{}, filter)
	if err != nil {
		return err
	}`

`type keyValuePair struct {
	key   string
	value string
}

var kvp keyValuePair

// Funcs is a function that implements Predicate.
type filterFuncs struct {
	// Create returns true if the Create event should be processed
	CreateFunc func(event.CreateEvent) bool

	// Delete returns true if the Delete event should be processed
	DeleteFunc func(event.DeleteEvent) bool

	// Update returns true if the Update event should be processed
	UpdateFunc func(event.UpdateEvent) bool

	// Generic returns true if the Generic event should be processed
	GenericFunc func(event.GenericEvent) bool
	Filter      keyValuePair
}

func keyValueFilter(kvp *keyValuePair) func(*filterFuncs) {
	return func(f *filterFuncs) {
		f.Filter.key = kvp.key
		f.Filter.value = kvp.value
	}
}

func newFilter(opts ...func(*filterFuncs)) *filterFuncs {
	f := &filterFuncs{}
	for _, opt := range opts {
		opt(f)
	}
	return f
}


func (p filterFuncs) Create(e event.CreateEvent) bool {
	labels := e.Meta.GetLabels()
	if val, ok := labels[p.Filter.key]; ok {
		if val == p.Filter.value {
			return true
		}
	}
	return false
}`

**Comment by DirectXMan12** [comment]
That's just like a predicate, though -- it doesn't actually get you most of the benefits of the filtering that people are asking for here, since it doesn't ask for server-side filtering.

**Comment by pickledrick** [comment]
I know... As I said above the code block

> I will follow this to understand how this is properly implemented and any questions from a user or testing perspective please ask and I'll do my best to assist. In the interim I've implemented this for my own use case.

**Comment by shawn-hurley** [comment]
bumping this feature request:

> allow users to turn off auto-caching, make them explicitly get filtered caching clients if they want (doable, more work for users). This potentially lets us allow users to specify that they don't want the client to ever cache a particular object (could encourage wrong patterns).

I think this is a viable option, but I wonder if we could have a more straightforward pattern like a user specifies a watch with a label. If they do, then we use the label-filtered cache for that specific GVK. If another watch is created without that label-filter, then we will error out and not establish the watch. The most significant caveat that I see is the client will only use the label filtered cache. We would need to make that clear in the documentation, or is there some other mechanism to alert the user to this.

**Comment by DirectXMan12** [comment]
the main issue with that approach is that it makes it so that certain controllers co-habitating suddenly breaks things, which is less than optional.  Still, I'm not sure that there's a good solution here, so we may have to go with the least-sub-optimal solution

**Comment by shawn-hurley** [comment]
What if we made the restriction explicit on the manager or during cache creation? Does this feel like the restriction on a namespace that we do now?

**Comment by DirectXMan12** [comment]
yeah, that could work, potentially, if it solves your usecase

**Comment by lulf** [comment]
I have a similar need for being able to specify namespace for watches (similar to https://github.com/kubernetes-sigs/controller-runtime/issues/124#issuecomment-417438810). I've been playing around with that in #692, but it could perhaps be made more generic than what is there at present. My main motivation for watching per namespace is to ensure I can grant controllers only the minimal permissions they strictly need (i.e. filtering by namespace client-side is not sufficient)

**Comment by alvaroaleman** [comment]
@DirectXMan12 re https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-451336202: Would it be another option to make the cache Reader smartly detect options that could be used to filter informers (namespace, labelSelector, fieldSelector), check if we have a cache for those already, if yes use it, if not fall back to unfiltered cache (which means creating it if it doesn't exist yet)?

**Comment by lulf** [comment]
How about an API something like this:

```
client.Watch(source.NewKind(&v1.Pod{}, client.InNamespace("namespace1")), ...)
client.Watch(source.NewKind(&v1.Pod{}, client.InNamespace("namespace2"), client.MatchingLabels(labelMap), ...)
```

The options are passed down to the informer map which will create additional caches if they are not covered with any existing informer.

**Comment by lulf** [comment]
Here is a more detailed design sketch I'd love to get more feedback on. I have split the requirements in 2 (I use the term 'filter' to mean watch/list filters like namespace, labels, field selector etc.):

1. Ability to create watches with different filters for different GVKs
2. Ability to create watches with different filters for the same GVK

For the first requirement, there is not really any API change needed IMO. However, for the second requirement, there are a few corner cases that must be taken into account. 

Lets assume watch A and B with different filters are created (in order) for the same GVK. Then, the following can happen:

* Conflict disjoint filters: A(key=foo) B(key=bar) - In this case watch A and B need to use different informers
* Superset filters: A(key=foo) B(key=foo,key2=bar) - In this case watch B should be able to re-use informer for A and add predicates for its conditions
* Superset filters reverse/conflicting order: A(key=foo,key2=bar) B(key=foo) - In this case A and B could use different informers _or_ the informer for A is removed and a new informer for B is created and creating predicates for A. 
* Intersecting filters? - I don't really have a good example of this.
 
Resolving the conflicts by returning an error may be sufficient for most cases. If not, we need a good way to signal users of error conditions.

(IMO, the best user experience would be if it was possible for multiple informers to share the same cache. That way, as long as duplicate cache events were handled properly (i.e. using metadata.resourceVersion?), one could use the same cache client.)


## Proposed design - static GVK delegation

Create mapping of GVK -> Filters when creating the cache/manager. A new type DelegateCache could take the following mapping as parameter:

```
NewDelegateCache(defaultFilters []Filter, gvkToFilter map[schema.GroupVersionKind][]Filter) Cache
```

The `Filter` type would basically be something like ListOpts and give the ability to restrict things like namespace, labels etc. for different types.

With this design, the cache filters are the 'hard' limits on what can be filtered on, and its not possible to use conflicting filters for the same GVK.

This would also not require an API change. When creating watches, the pre-configured filters will be used depending on type.

More specific filtering can be done using predicates as today.

It does not solve the second requirement of using different filters for the same GVK.

## Proposed design - on-demand delegation

I think a modification to the API is required in order to allow for different filters for the same GVK. One could extend the current controller api with the ability to supply filters, something like:

```
controller.Watch(source.NewKind(&v1.Pod{}, filter.InNamespace("namespace1"), filter.MatchingLabels(labelMap), &handler.EnqueueRequestForObject{})
```

Moreover, the cache/manager may be configured with default filters (i.e. replace 'namespace' with a list of filters).

The cache implementation can examine the filters provided in GetInformer and make a decision on what to do according to the different corner cases. Alternatives for conflict resolution if existing informers cannot be used:

* Return error from controller.Watch, unless cache was created with a 'AllowDuplicateCache' flag, in which case it is assumed the user knows that the cache client cannot be used to lookup objects.
* Have controller.Watch also return a pointer to the cache client that should be used for looking up objects for that particular watch.

### Example usage

#### Watching the same GVK with complementing watches

```
m, err := manage.New(cfg, manager.Options {
   defaultFilters: []Filter{},
})
...
c.Watch(source.NewKind(&v1.Pod{}, source.InNamespace("namespace1"), ...)
c.Watch(source.NewKind(&v1.Pod{}, source.InNamespace("namespace1"), source.MatchingLabels(labelMap)), ...)
```

The first Watch will create a new cache with the filters. The second watch could use the same informer and create predicates to do client-side filtering.

#### Watching the same GVK with conflicting watches due to order of creation

```
...
c.Watch(source.NewKind(&v1.Pod{}, source.InNamespace("namespace1"), source.MatchingLabels(labelMap)), ...)
c.Watch(source.NewKind(&v1.Pod{}, source.InNamespace("namespace1")), ...)
```

The first Watch will create a new cache with the filters. Depending on the conflict resolution, either return error or return handle of new cache to client.

#### Watching different GVKs with different options:

```
c.Watch(source.NewKind(&v1.Pod{}), ...)
c.Watch(source.NewKind(&v1.Secret{}, source.InNamespace("namespace1")), ...)
```

The first watch will just use the defaults, the second will create a new cache and return handle. However, since its a different type, one could have the cache create a delegated mapping.

@shawn-hurley @alvaroaleman @DirectXMan12  thoughts?

**Comment by shawn-hurley** [comment]
I like the idea of on-demand delegation, I am worried that implementation is going to get really messy to handle the use cases. 

> Watching the same GVK with conflicting watches due to order of creation

So if the first call to watch is more restrictive then the second case, we will error out?

What does it look like if we try and handle it?

**Comment by lulf** [comment]
> So if the first call to watch is more restrictive then the second case, we will error out?
>
> What does it look like if we try and handle it?

The alternatives I can think of are:

* Return error. Easy but maybe it feels a bit restrictive.
* Duplicate cache, potentially returning a client handle to avoid looking up in the wrong cache. Removes the restrictive handling, but at the expense of multiple caches.
* Create new informer for the less restricted watch, and modify the first watch to use predicates on the new informer. I think this could be messy if we worry about duplicate events.

**Comment by alvaroaleman** [comment]
@lulf The tricky part here is not so much how exactly we change the cache, its mostly about finding a good solution for the cache reading client to determine which cache to use, see https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-451336202

Apart from the options Solly outlined, I also suggested this:

> Would it be another option to make the cache Reader smartly detect options that could be used to filter informers (namespace, labelSelector, fieldSelector), check if we have a cache for those already, if yes use it, if not fall back to unfiltered cache (which means creating it if it doesn't exist yet)?

I personally would like to see a gdoc that outlines the ideas we have on how the cache reading client knows which cache to use and ignores how we change the cache itself or the watch calls, as that is the easy part. We can then discuss the options in detail on the gdoc.

**Comment by vincepri** [comment]
/kind design

@lulf Would you be able to open a PR against controller-runtime with a design document?

**Comment by jkbschmid** [comment]
My team is also interested in this feature. We have a controller that watches a small set of secrets. However, overall the cluster has many (also larger) secrets which
increases our pod requests/limits drastically, because they will all be cached. 
In our use case, using a separate cache for each filtered watch would absolutely suffice, because the number of secrets we are interested in is small. Therefore, we only have very little additional memory overhead because of duplication.
 @lulf Is there any ongoing work atm?

**Comment by lulf** [comment]
@jkbschmid I've not found time or need to work on this since my last proposal. We have a workaround 'delegating cache' that solves a subset of the requirements (i.e. we can at startup time set which GVKs we want to watch globally)[1]. 

FYI if you haven't seen this already: if you know which namespaces you need to watch up front, you can have a look at the multiNamespaceCache in pkg/cache/multi_namespace_cache.go

[1] https://github.com/EnMasseProject/enmasse/tree/master/pkg/cache

**Comment by arturobrzut** [comment]
My team is also interested in this feature. We have a controller that watches a small set of secrets. However, overall the cluster has many (also larger) secrets which
increases our pod requests/limits drastically, because they will all be cached. about 100MB per 1k secrets.
Is there any plan to fix/implement it in the near future?

**Comment by estroz** [comment]
I think a prototype with docs/tests is a good way to kick off the discussion on choosing one solution over the other, and would give me/us a chance to understand limitations of a particular solution. This problem is hard to reason about without some code to back up a solution.

This is more or less what everyone seems to be saying about informer creation (from https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-451336202):

>Have a list-options watch predicate, smartly detect the presence of that (in some generic way) and pass it down to `GetInformer`. If we already have a global informer, just use that. If we don't have a global informer, create a new filtered informer. We delay creation of informers to figure out if one person needs a global informer, and just use that, to allow splitting and combining seamlessly.

As for the cache `Reader` solution, I like the idea of smartly detecting which cache to use based on selectors/namespaces supplied to `Get()/List()`, like @alvaroaleman [suggested](https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-557661685):

>make the cache `Reader` smartly detect options that could be used to filter informers (namespace, labelSelector, fieldSelector), check if we have a cache for those already, if yes use it, if not fall back to unfiltered cache

If anyone would like to expand/comment on the above two parts of the prototype, or voice any objects, feel free.

**Comment by camilamacedo86** [comment]
I really liked the idea made in the comment https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-572978846 +1. 

```go 
		controller.Watch(source.NewKind(&v1.Pod{}, filter.InNamespace("namespace1"),
			filter.MatchingLabels(labelMap), &handler.EnqueueRequestForObject{})
```

**Comment by taylormgeorge91** [comment]
@estroz Is this still progressing? We are keen to see this feature enabled.

**Comment by estroz** [comment]
@taylormgeorge91 I haven't had as much time as I'd like to work on this, but I did just post a rough prototype (#1178). Feel free to critique.

**Comment by pagarwal-tibco** [comment]
I also have a use case of watching pods running on a node and not watch all the pods in the cluster.
This will limit the number of kubernetes resources needs to cached/watched and processed. My use case is of having daemon-set watching pods on current node, hence I am looking for a solution like having a fieldSelector for the resources being watched/cached and reconciled.

I see that kubernetes client-go library provides similar functionality with func NewListWatchFromClient(c Getter, resource string, namespace string, fieldSelector fields.Selector) *ListWatch in package <client-go>/tools/cache. Is there a similar way to achieve this using kubebuilder?

It would be very useful to have this feature which I think is already supported by underlying kubernetes client-go library. This will also help in reducing cache, memory footprint and CPU requirements when there are huge number of pods in the cluster.

**Comment by pagarwal-tibco** [comment]
Any updates on this?

**Comment by qinqon** [comment]
I have try a PR to specify a fieldselector at manager build time https://github.com/kubernetes-sigs/controller-runtime/pull/1404.

**Comment by timebertt** [comment]
New PR: #1435

**Comment by invidian** [comment]
#1435 is now merged, so is this resolved?

**Comment by taylormgeorge91** [comment]
It is being worked into a release currently @invidian 

Looking at the tags there is a v0.9.0-beta available if you want to test.

**Comment by invidian** [comment]
>Looking at the tags there is a v0.9.0-beta available if you want to test.

Thanks, will do!

**Comment by estroz** [comment]
>#1435 is now merged, so is this resolved?

@invidian yes I believe this is resolved.

/close

**Comment by roee88** [comment]
It seems like the current solution doesn't address the use case mentioned in
https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-557656216.  

It should be possible to create a namespace scoped client in ListFunc and WatchFunc if there is a field selector for `metadata.namespace` (vs the current logic of just looking at the global namespace field). Is that reasonable?

**Comment by alvaroaleman** [comment]
@roee88 what was merged allows to set a FieldSelector so yes, this is possible

**Comment by roee88** [comment]
To clarify, I _suspect_ that without affecting the parameters to NamespaceIfScoped, the selector opts has no effect on the required rbac (cluster role bindings vs role bindings). For example here:

https://github.com/kubernetes-sigs/controller-runtime/blob/64b1c729991a0316f1500ce5fc52544cd86c5fce/pkg/cache/internal/informers_map.go#L282-L288

My question is whether changing the code here makes sense. Specifically for the case where ip.namespace is empty, the value from a `metadata.namespace` field selector should be used (if exists).

**Comment by alvaroaleman** [comment]
> My question is whether changing the code here makes sense. Specifically for the case where ip.namespace is empty, the value from a metadata.namespace field selector should be used (if exists).

That sounds reasonable

**Comment by thesuperzapper** [comment]
My recommendation is to do something similar to this PR in external-secrets:

- https://github.com/external-secrets/external-secrets/pull/4086

## Disable Caching Manager's Default Client

You can disable the cache for specific resource kind in your [`manager.Manager`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Manager) default client using `DisableFor` in the [`client.CacheOptions`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#CacheOptions):

For example, your outer `main()` function might look like this:

```go
import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"log/slog"
	"os"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
)

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
	restConfig := ctrl.GetConfigOrDie()
	scheme := runtime.NewScheme()

	// add default Kubernetes types to the scheme
	if err := clientgoscheme.AddToScheme(scheme); err != nil {
		logger.Error("failed to add Kubernetes types to scheme", "error", err)
		os.Exit(1)
	}
	// add your custom types to the scheme
	//if err := XXXXv1beta1.AddToScheme(scheme); err != nil {
	//	logger.Error("failed to add XXXX types to scheme", "error", err)
	//	os.Exit(1)
	//}

	ctrlOpts := ctrl.Options{
		Scheme: scheme,
		Client: client.Options{
			Cache: &client.CacheOptions{
				// this disables caching for all Secrets and ConfigMaps
				// as caching all secrets can take a LOT of memory in a large cluster
				DisableFor: []client.Object{
					&corev1.Secret{},
					&corev1.ConfigMap{},
				},
			},
		},
		Metrics: metricsserver.Options{
			BindAddress: "0", // not required, just for example
		},
		HealthProbeBindAddress: "0",   // not required, just for example
		LeaderElection:         false, // not required, just for example
	}

	// create a new manager
	mgr, err := ctrl.NewManager(restConfig, ctrlOpts)
	if err != nil {
		logger.Error("unable to create manager", "error", err)
		os.Exit(1)
	}

	//
	// ADD THE BuildManagedSecretClient() FUNCTION HERE
	// SEE THE NEXT SNIPPET FOR AN EXAMPLE
	//

	// start the manager
	logger.Info("starting manager")
	err = mgr.Start(ctrl.SetupSignalHandler())
	if err != nil {
		logger.Error("unable to start manager", "error", err)
		os.Exit(1)
	}
}
```

## Example of Filtered Cached Client

You can construct a new filtered client using [`ByObject`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache#ByObject) from [`cache.Options`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache#Options). 

(__WARNING:__ a client which uses a filtered cache will be completely unable to see resources in the cluster which don't match the cache, even if they exist)

For example, here is the one from external-secrets which only caches secrets with the `reconcile.external-secrets.io/managed=true` label:

```go
import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/selection"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func BuildManagedSecretClient(mgr ctrl.Manager) (client.Client, error) {
	// secrets we manage will have the `reconcile.external-secrets.io/managed=true` label
	managedLabelReq, _ := labels.NewRequirement("reconcile.external-secrets.io/managed", selection.Equals, []string{"true"})
	managedLabelSelector := labels.NewSelector().Add(*managedLabelReq)

	// create a new cache with a label selector for managed secrets
	// NOTE: this means that the cache/client will be unable to see secrets without the "managed" label
	secretCacheOpts := cache.Options{
		HTTPClient: mgr.GetHTTPClient(),
		Scheme:     mgr.GetScheme(),
		Mapper:     mgr.GetRESTMapper(),
		ByObject: map[client.Object]cache.ByObject{
			&corev1.Secret{}: {
				Label: managedLabelSelector,
			},
		},
		// this requires us to explicitly start an informer for each object type
		// and helps avoid people mistakenly using the secret client for other resources
		ReaderFailOnMissingInformer: true,
	}
	secretCache, err := cache.New(mgr.GetConfig(), secretCacheOpts)
	if err != nil {
		return nil, err
	}

	// start an informer for secrets
	// this is required because we set ReaderFailOnMissingInformer to true
	_, err = secretCache.GetInformer(context.Background(), &corev1.Secret{})
	if err != nil {
		return nil, err
	}

	// add the secret cache to the manager, so that it starts at the same time
	err = mgr.Add(secretCache)
	if err != nil {
		return nil, err
	}

	// create a new client that uses the secret cache
	secretClient, err := client.New(mgr.GetConfig(), client.Options{
		HTTPClient: mgr.GetHTTPClient(),
		Scheme:     mgr.GetScheme(),
		Mapper:     mgr.GetRESTMapper(),
		Cache: &client.CacheOptions{
			Reader: secretCache,
		},
	})
	if err != nil {
		return nil, err
	}

	return secretClient, nil
}
```
