### ISSUE TITLE
controller histogram buckets configuration

### ISSUE THREAD

**Issue by terinjokes** [kubernetes-sigs/controller-runtime#258]
Metrics are created for the controller's workqueue, using Prometheus's [default buckets](https://github.com/kubernetes-sigs/controller-runtime/blob/b497fd58b9d76e0af8a4cba21c595d13cf094307/pkg/internal/controller/metrics/metrics.go#L47-L57). Unfortunately, the default buckets are poorly chosen for event processing.

> The default buckets are tailored to broadly measure the response time (in seconds) of a network service.

This can easily result in metrics that are extremely coarse. In a controller I was working on today, every single reconcile was faster than the smallest bucket:

```
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="0.005"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="0.01"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="0.025"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="0.05"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="0.1"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="0.25"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="0.5"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="1"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="2.5"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="5"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="10"} 31
controller_runtime_reconcile_time_seconds_bucket{controller="application",le="+Inf"} 31
```

It is possible to change the default buckets by modifying [DefBuckets](https://godoc.org/github.com/prometheus/client_golang/prometheus#pkg-variables) in `init`, as my `init` will be called after the `DefBuckets` variable has been initialized, but before the controllermetrics package `init`. But this is a very heavy handed brush, changing the defaults of all histograms.

I propose two paths forward:

1. Allow the user to pass their own metrics to the controller, with the current collectors used if the none are provided.
2. Alternatively, move the current package outside of the internal package, This will allow users to call [Unregister](https://godoc.org/github.com/prometheus/client_golang/prometheus#Registry.Unregister) and then assign a replacement.

My preference would be the first option, as the change to the system is would be more easily understood.

**Comment by mengqiy** [comment]
The 1st option makes sense to me.

**Comment by DirectXMan12** [comment]
I think we can *probably* choose some better buckets, too.  This smae discussion is being had right now in the main k/k repo ;-).

**Comment by DirectXMan12** [comment]
It seems to me like exposing the exact mechanics of how we observe metrics is exposing an implementation detail as public API (at least, that's my gut feeling), particularly since the only way to actually change the bucket definition would be to expose the individual metrics at a API level.  That would mean that we'd be tied to a particular set of metrics with a particular interface for measuring them (and it would mean that only a major revision could change/remove metrics, but it's unclear if that's a bad thing).  If we ever wanted to switch to, say, contextual metrics measurement, we couldn't without a major version rev, even if we didn't actually change the metrics exposed.

My instinct here is to fix our buckets, and wait for more evidence that a "one-size-fits-all" solution won't work here, especially since we have little evidence that our currently buckets are *correct* for many cases.  The Kubernetes SLO for request latency against the API server is `1s`, IIRC, and that's on the high end.  This bucket selection seems to be poor in that case.  k/k is discussing the same thing right now in the switch from summaries to buckets.

**Comment by mengqiy** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/63750 and https://github.com/kubernetes/kubernetes/pull/67476 are the upstream issue and PR.

**Comment by DirectXMan12** [comment]
/remove-lifecycle stale

looks like kube has fixed this upstream, so we can follow suit

/good-first-issue

**Comment by irajdeep** [comment]
Hi @DirectXMan12 
We also have a use-case where we need more time duration buckets (> 10secs) for `controller_runtime_reconcile_time_seconds_bucket` histogram. 
Should we add the buckets to controller-runtime metrics in accordance with the upstream changes done in this PR: https://github.com/kubernetes/kubernetes/pull/73638. ?
