### ISSUE TITLE
Support newer patch versions of Kubernetes in `setup-envtest`

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/controller-runtime#2583]
Right now, we are hitting transient errors with the kube-apiserver due to our testing of CEL. We are using `setup-envtest` to download the binaries needed for `setup-envtest` from the Google Cloud mirror. 

The issues we are hitting with respect to CEL and the apiserver are documented in: https://github.com/kubernetes/kubernetes/pull/114857. This change was cherry-picked across releases which can be seen at the bottom of the issue here: https://github.com/kubernetes/kubernetes/issues/114661.

From looking at the `setup-envtest` manifest, I can see that `setup-envtest` is often not taking up newer cherry-picked releases into the mirror, meaning that this fix to the `kube-apiserver` that was added in `1.25.6`, `1.26.6`, etc. is not released with `setup-envtest`, which means that we are still using an older version of the apiserver that is buggy and causing CI failures.

It would be awesome if, as Kubernetes released new cherry-picks of each of these binaries, `setup-envtest` would mirror these binaries over to the Google Cloud mirror so that we could always have the most up-to-date version of the binary running against any given minor version that we are testing.

**Comment by sbueringer** [comment]
Agree, this would definitely be nice. controller-runtime only contains the setup-envtest binaries though. The Kubernetes binaries are published via the tools-release branch in the kubebuilder repo: https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases

So probably we should move this issue over there (@camilamacedo86 WDYT?)

**Comment by camilamacedo86** [comment]
Hi @jonathan-innis, 

I wanted to update you regarding the binaries for our project. All binaries that have been built are available at https://storage.googleapis.com/kubebuilder-tools ( branch of kubebuilder project ). As @sbueringer mentioned, these are built whenever we merge a PR into the [tools-releases branch of kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases/). You'll notice that we continually generate new versions using the latest updates. However, it's important to note that we do not backport or release older patches due to the current implementation constraints.

On a related note, regarding the generation of these binaries, **I believe that the primary responsibility falls under Controller Runtime rather than Kubebuilder (ENV TEST lib implementation is in Controller-Runtime)**. Kubebuilder primarily acts as a consumer of Controller Runtime as ENV TEST, utilizing it more like a library.

That being said, your suggestion caught my attention, and I genuinely support the idea of bringing changes to our current process. **In an ideal scenario, I'd advocate for drafting a formal proposal to shift the binary generation responsibility to Controller-Runtime. This move seems more aligned with the domain of responsibilities.**

**However, if you're inclined to propose alternative methods or improvements to our current process, I encourage you to do so**. Feel free to open PRs against the relevant branch and share your thoughts. Your contributions and ideas are always welcome and highly valued in our community.

Looking forward to your thoughts and contributions.

Best regards,

**Comment by sbueringer** [comment]
I wonder if there's a way to consume Kubernetes release artifacts directly

**Comment by jonathan-innis** [comment]
@sbueringer I was thinking the same thing. I'm curious why we are repeating the work that's required to re-produce and mirror these binaries if we could just grab the latest released version within a passed-through minor version.

**Comment by sbueringer** [comment]
Not sure if k/k releases etcd / kube-apiserver etcd as individual binaries, but pulling container images and extracting them might be an option. Needs some investigation.

**Comment by camilamacedo86** [comment]
> @sbueringer I was thinking the same thing. I'm curious why we are repeating the work that's required to re-produce and mirror these binaries if we could just grab the latest released version within a passed-through minor version.

Because we need a "bundle" with those binaries that can run in more SO/archs which are not provided by them.
That was the initial motivation. By looking the code you can see that we build the binaries for the archs. 

![Screenshot 2023-11-23 at 12 42 17](https://github.com/kubernetes-sigs/controller-runtime/assets/7708031/9466a9c2-d580-4aba-956d-c77930c2b472)

Do we have now `kube-apiserver (k8s)`, `kubectl`, `etcd` provided by the projects for all those envs?

**Comment by jonathan-innis** [comment]
> Following is what seems required in POV to achieve what you are asking here

Yeah, I see the concern here with all the complexity we are talking about. We are basically talking about a re-write of the way that the repo is maintained and the workflow is released. Definitely seems like a cost/benefit trade-off given the number of people who I assume are maintaining and contributing to the project and the benefit to users testing (assuming they need the newer patch releases). 

This one became of particular interest to us because of the bug that I outlined above which causes consistent flakes in our CI testing but I can see the case that these instance are few and far between. 

> which they do not provide

As an aside, it seems surprising to me that kubebuilder is supporting and publish more diverse binaries than the upstream Kubernetes release process. Is there a reason they don't publish through a similar mechanism and then we just get to pull all of them for free without having to build some forms of them manually?

**Comment by camilamacedo86** [comment]
Hi @jonathan-innis,

> Yeah, I see the concern here with all the complexity we are talking about. We are basically talking about a re-write of the way that the repo is maintained and the workflow is released.

The complexities are not only about the effort to change:
- **Design of Data and Triggers for Retroactive Patching:** We need a well-thought-out design for data structures and triggers that would allow for retroactive patching. I encourage you to review the current design to understand how this can be implemented.
- **Manual Effort vs Automatic Triggers:** If we continue with manual efforts, we can trigger updates as needed. However, this approach doesn't guarantee consistency. To ensure regular and reliable updates, we should consider implementing automatic triggers. This raises the question: which version of ETCD is optimal for our needs? Additionally, how do we handle situations where there isn't a compatible ETCD release available?
- **Cost to maintain:** As you see it has a cost. I would really advocate for we change the current solution for a solution where we no longer need to generate the tairbal and it could be generate locally for example. 

> As an aside, it seems surprising to me that kubebuilder is supporting and publish more diverse binaries than the upstream Kubernetes release process. Is there a reason they don't publish through a similar mechanism and then we just get to pull all of them for free without having to build some forms of them manually?

Our primary task is to pull and generate the tarball. Additionally, we build for architectures that are not natively supported by the project, specifically for cases where the project does not supply the necessary binaries. For these instances, I suggest we open an issue with each project that lacks support for certain architectures, proposing that they start providing binaries for these additional platforms. (we can try)

 ### 💡 Enhancement of Previous Suggestion/Proposed Solution:
_______

We propose a solution where users generate the tarball locally using a Dockerfile. This approach eliminates the need for us to maintain these artifacts, allowing users the flexibility to generate them for any version they require.

We can integrate the Dockerfile as part of the setup environment test script in controller-runtime. Alternatively, incorporating it into the Kubebuilder scaffold is also a viable option. However, it's important to note that if the Dockerfile is only included in the Kubebuilder scaffold, it may not be accessible to users who rely on controller-runtime and envtest but do not use Kubebuilder.

@sbueringer wdyt? ^

**Comment by sbueringer** [comment]
Some context: 
> Hey folks,
> we are currently experimenting a bit on setup-envtest because the envtest binaries are today hosted on the Google-owned kubebuilder repository.
> 
> Going forward we will start hosting the envtest binaries on controller-tools releases. We currently also plan to move setup-envtest to controller-tools as it fits better there. As part of that we will build & publish setup-envtest binaries on controller-tools releases in the future. This should also give proper versioning.
> https://github.com/kubernetes-sigs/controller-runtime/issues/2646#issuecomment-2066758692

When implementing the envtest binary publishing in controller-tools we also implemented it in a way that it's very easy to publish binaries for more versions of Kubernetes.

An example can be found here: https://github.com/kubernetes-sigs/controller-tools/pull/924

(Please note that we have some work to do before setup-envtest will be able to consume envtest binaries from controller-tools releases)

**Comment by sbueringer** [comment]
@jonathan-innis 

Recently merged https://github.com/kubernetes-sigs/controller-runtime/pull/2811

So now envtest binaries from the new location (controller-tools release attachments) can be used

For available releases please either check via setup-envtest or you can also see them here: https://github.com/kubernetes-sigs/controller-tools/releases

If you additional versions, feel free to open a PR against controller-tools, for prior art see: https://github.com/kubernetes-sigs/controller-tools/pull/956 or any of the other PRs: https://github.com/kubernetes-sigs/controller-tools/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+%22Release+envtest%22

Closing the issue as this should cover what we need. Please let me know if I'm missing anything then we can reopen

/close
