### ISSUE TITLE
Request for v0.17.0

### ISSUE THREAD

**Issue by Neo2308** [kubernetes-sigs/controller-runtime#2640]
Could we create the new release which contains the bump of k8s dependencies to 1.29.x?

Related PRs:
* https://github.com/kubernetes-sigs/controller-runtime/pull/2612
* https://github.com/kubernetes-sigs/controller-runtime/pull/2615
* https://github.com/kubernetes-sigs/controller-runtime/pull/2621

**Comment by Neo2308** [comment]
@sbueringer is this something you could help with?

**Comment by troy0820** [comment]
/retitle Request for v0.17.0

main has the latest. Do you need the release to be done before migrating to the hash in main? Can you use @<hash>? I’m not sure of the release scheduled but I believe the coordination around doing this is a lot of effort because of the minor changes associated with what needs to go in, etc.

**Comment by sbueringer** [comment]
There is no fixed date as of now. But we're working on finalizing a few PRs that should make it into v0.17.

My guess would be that the release should be out within 1 or 2 weeks.

**Comment by sbueringer** [comment]
Done: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.17.0

/close
