### ISSUE TITLE
How to iterate over ObjectList

### ISSUE THREAD

**Issue by just1900** [kubernetes-sigs/controller-runtime#2697]
```
list := c.Res.NewList()
c.cli.List(context.Background(), list)
```

I have a generic function that returns `ObjectList` interface, and trying to iterate over the `ObjectList`. However it seems that there is no way to get items.

**Comment by troy0820** [comment]
/kind support 

I don't believe you can because you don't have access to the type's items returning the interface like this.  There is no method to get the items to then iterate over.

What are you trying to accomplish with the use of generics to abstract away the type you need while returning the interface?

**Comment by just1900** [comment]
Close this one as I have abandoned the generic function. For those seeking similar abstraction, you can use `unstructured` instead.

```
        list := &unstructured.UnstructuredList{}
	list.SetGroupVersionKind(gvk)
	err := c.cli.List(context.Background(), list)
```
