### ISSUE TITLE
ENVTest - cannot delete PVCs in BDD test

### ISSUE THREAD

**Issue by rahulsb** [kubernetes-sigs/controller-runtime#2854]
In my BDD test of operator, I would like to delete the PVCs created before running nee test as the cleanup. While deleting the PVC they remains in the pending state. Are there any workaround or solutions using ENVTest.

Using : sigs.k8s.io/controller-runtime v0.16.5

**Comment by sbueringer** [comment]
I assume usually the kube-controller-manager does something there? (it doesn't exist in envtest)

**Comment by Yesphet** [comment]
This is because the finalizer `kubernetes.io/pvc-protection` is automatically added when creating the PVC, but there is no controller to handle the finalizer when deleting in the ENVTest environment, so the PVC remains in pending. You can perform an update or patch to remove the finalizer of the PVC before deleting.

**Comment by rahulsb** [comment]
> This is because the finalizer `kubernetes.io/pvc-protection` is automatically added when creating the PVC, but there is no controller to handle the finalizer when deleting in the ENVTest environment, so the PVC remains in pending. You can perform an update or patch to remove the finalizer of the PVC before deleting.

thanks @Yesphet , this solution works.

**Comment by sbueringer** [comment]
Great!

/close
