### ISSUE TITLE
API request: access to the raw REST client for a type

### ISSUE THREAD

**Issue by coderanger** [kubernetes-sigs/controller-runtime#299]
I'm imagining something like `mgr.GetClient().GetRawClientFor(obj)` which pretty much returns `c.cache.getObjMeta(obj)` as used in TypedClient. This would allow calling methods not exposed by the c-r client layer (such as PATCH requests) without the full complexity of initializing a client-go REST client.

**Comment by grantr** [comment]
This would make committing to the CR client interface less scary since there's always a trap door available.

Ideally this would also support the dynamic client. Either `GetRawClientFor` method could return the resource interface corresponding to the given Unstructured object, or a separate `GetDynamicClient` method could be made available.

**Comment by DirectXMan12** [comment]
there's always `"pkg/client/apiutil".RestClientForGVK`, although it's slightly less convenient.  I'm not necessarily keen on the idea of putting `GetRawClientFor` in the `Client` interface, but we should make this easier.

/kind feature
/priority important-longterm
