### ISSUE TITLE
Error while running tests 

### ISSUE THREAD

**Issue by Antirecord** [kubernetes-sigs/controller-runtime#3005]
Good evening! I have several controllers with corresponding tests, but the tests are not running successfully. I've tried many solutions, but nothing has worked so far. Could you advise on what might be causing this issue?

[logs.txt](https://github.com/user-attachments/files/17680029/logs.txt)

apiserver, kubectl version = 1.31.0
etcd version = 3.5.15

go version = trying with 1.22.4 and 1.23.2

sigs.k8s.io/controller-runtime = v0.19.0
CONTROLLER_TOOLS_VERSION ?= v0.16.4

**Comment by alvaroaleman** [comment]
Please re-post your question to our [Discussion Forums](https://discuss.kubernetes.io).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on GitHub is making it difficult for us to use
issues to identify real bugs.

Members of the Kubernetes community use Discussion Forums to field
support requests. Before posting a new question, please search these for answers
to similar questions, and also familiarize yourself with:

  * [user documentation](https://kubernetes.io/docs/home/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

Again, thanks for using Kubernetes.

/triage support
/close
