### ISSUE TITLE
auto-owner-reference setter

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#455]
We might want to consider a mode or something that automatically sets owner references.  It's not clear exactly what that looks like (client option?  wrapping client?), but it's something to think about.

/kind feature

**Comment by shawn-hurley** [comment]
I really like this idea.

We need to make sure that we do the correct thing and make sure that namespaced resources are not owners of cluster scoped resources. I think how we want to handle this scenario either error out or hide this complexity will determine the best design. For instance, if we tried to hide the complexity, then a wrapping client would make the most sense to me because everything that can get the owner ref should. If we want to error out, I think the client options is the best, so a user has to add it to the correct resources themselves. 

WDYT?

**Comment by DirectXMan12** [comment]
well, client option is "easy" in that we can always build the wrapping client on top of it

**Comment by vincepri** [comment]
Closing this as setting owner references should be easy enough within reconciler code

/close
