### ISSUE TITLE
Implement helpers functions for using finalizers

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/controller-runtime#485]
Code for implementing finalizers can be captured in couple of helpers functions in controller-runtime. Helpers functions can help in examining, adding and removing finalizers as suggested in [the PR](https://github.com/kubernetes-sigs/kubebuilder/pull/778/files#r292646664)

**Comment by negz** [comment]
We have a few finalizer helper functions in our controller-runtime project Crossplane - I'd be happy to submit a PR to add them to controller-runtime.

```go
// AddFinalizer to the supplied Kubernetes object's metadata.
func AddFinalizer(o metav1.Object, finalizer string) {
	f := o.GetFinalizers()
	for _, e := range f {
		if e == finalizer {
			return
		}
	}
	o.SetFinalizers(append(f, finalizer))
}

// RemoveFinalizer from the supplied Kubernetes object's metadata.
func RemoveFinalizer(o metav1.Object, finalizer string) {
	f := o.GetFinalizers()
	for i, e := range f {
		if e == finalizer {
			f = append(f[:i], f[i+1:]...)
		}
	}
	o.SetFinalizers(f)
}
```

**Comment by droot** [comment]
@negz Thanks for the offer. Pl. do. But API should take `runtime.Object` as input instead of `metav1.Object` because thats the abstraction all other CR's APIs operate on. Also, pl. take a look at @DirectXMan12 's suggestion in the linked PR.

**Comment by negz** [comment]
> API should take runtime.Object as input instead of metav1.Object because thats the abstraction all other CR's APIs operate on.

I believe taking `runtime.Object` would require us to attempt to transform the object via `metav1.Accessor()` inside the utility function, which means we'd have to return an error and thus the caller would be stuck handling (or ignoring) an error every time they wanted to set a finalizer.

Is it actually common for controllers to be treating objects under reconciliation as `runtime.Object`? Speaking personally, I'd opt not to use a utility function that took `runtime.Object` simply to set finalizers because in 99% of cases I'm reconciling an object that I know satisfies `metav1.Object`.

**Comment by DirectXMan12** [comment]
The main reason to use runtime.Object is not to force people to type assert or call `meta.Accessor` themselves.  We pass around `runtime.Object` because it's what most of the low-level core kube apimachinery interfaces work with.  It's mostly a side-effect of us consuming the low-level apimachinery.  That being said, it's fairly uncommon for someone *not* to have something that implements `metav1.Object`, so it may be ok here.

**Comment by alexeldeib** [comment]
@negz did you want to PR this? I can if not.

**Comment by alexeldeib** [comment]
Maybe less desirable because of additional cruft, but we could implement both, something like

```go
// bad naming, but illustrative
func AddFinalizer(o metav1.Object, finalizer string) {...}
func AddFinalizerWithError(o runtime.Object, finalizer string) error { 
    m, err := meta.Accessor(o)
    if err != nil {
        return err
    }
    AddFinalizer(m, finalizer)
}

func RemoveFinalizer(o metav1.Object, finalizer string) {...}
func RemoveFinalizerWithError(o runtime.Object,, finalizer string) {
func AddFinalizer(o runtime.Object, finalizer string) error {
    m, err := meta.Accessor(o)
    if err != nil {
        return err
    }
    RemoveFinalizer(m, finalizer)
}
```

**Comment by negz** [comment]
@alexeldeib Please feel free to take this!

**Comment by DirectXMan12** [comment]
fixed as per above
