### ISSUE TITLE
Downgrade controller-runtime in go.mod by `go get k8s.io/client-go@v12.0.0`

### ISSUE THREAD

**Issue by binoue** [kubernetes-sigs/controller-runtime#555]
Hi! I am using `controller-runtime` but encountered the problem below.

- Problem
  - running the `go get k8s.io/client-go@v12.0.0` downgrades controller-runtime from `v0.2.0-beta.4` to `v0.2.0-alpha.0`
  - `go get sigs.k8s.io/controller-runtime@v0.2.0-beta.4` returns the error below and also downgrades `client-go` from v12.0.0  to v11.0.1

- Error
```console
$ go get sigs.k8s.io/controller-runtime@v0.2.0-beta.4
# k8s.io/client-go/rest
../../../../pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

I think this is a bug and the solution below will resolve this bug.

- Solution
I think that the current `go.mod` file in controller-runtime is referring to the invalid client-go version which is `k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible`.
So fixing the reference to `client-go` in `go.mod` will solve this problem.

/kind bug

**Comment by DirectXMan12** [comment]
It shouldn't be referring to an invalid client-go version -- I believe it's just referring to a matching `kubernetes-1.y.z` tag, which is more reliable than trying to match the equivalent client-go semver-ish version to the other repos' `kubernetes-x.y.z` tags.  In general, we highly recommend that you don't try to use the semver client-go versions -- you'll cause yourself headaches with the other libraries.

**Comment by ymmt2005** [comment]
@DirectXMan12 
It is `controller-runtime` that references non-existing tag of `client-go` (v11.0.1) in its go.mod.

Please check existing tags of `client-go`; v11.0.1 does not exist.
https://github.com/kubernetes/client-go

**Comment by DirectXMan12** [comment]
right, that's a pseudo-version that got converted over from a real tag.  If you say `k8s.io/client-go kubernetes-1.14.1` in your `go.mod` file, and then run `go mod tidy`, Go will convert that non-semver tag (`kubernetes-1.14.1`) into a pseudo-version (`k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible`) using an algorithm detailed in https://tip.golang.org/cmd/go/#hdr-Pseudo_versions.

It does this so that it can continue to compare versions using a uniform algorithm.  So, we set all kubernetes dependencies to `kubernetes-1.14.1`.  This is the best way to make sure you don't have any weird conflicts.  Then, `go mod tidy` converts those to pseudo-versions.  Such is life when most of the `k8s.io/` dependencies don't use semver.

Trying to set `client-go` to a semver version, and everything else to non-semver has cause a *lot* of issues in the past.  It's not a good idea.  Again, we highly recommend that you avoid using the semver versions of client-go -- there's no real benefit, and they'll only cause you issues down the road.

**Comment by DirectXMan12** [comment]
We'll update to `kubernetes-1.15.x` tags shortly after we release v0.2.0 final.  At that point, we'll address any incompatibilities.

**Comment by DirectXMan12** [comment]
(closing for now, but if there's something you don't understand, feel free to continue to ask questions.  In the mean time, I'd highly recommend that you give the Go modules wiki page a read-through)

**Comment by ymmt2005** [comment]
@DirectXMan12 Got it.  Many thanks!

**Comment by binoue** [comment]
@DirectXMan12  Appreciated!

**Comment by ymmt2005** [comment]
BTW, `client-go` officially says that it should be got with its semver.

```
go get k8s.io/client-go@v12.0.0
```

https://github.com/kubernetes/client-go/blob/master/INSTALL.md#go-modules

**Comment by DirectXMan12** [comment]
Yeah.  We used to try to do that at various points in the past.  I invariably caused headaches after a bit.  It *might* be better with modules, but it's more reliably correct to use a uniform tag across all of them.
