### ISSUE TITLE
is there a way to make client.Get to not get from cache

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes-sigs/controller-runtime#585]
Hi, I have a case that I need to use `client.Get()` immediately after running `client.Status().Update()`.

The `client.Get()` will get the object from cache, this is not what I want.

The implementation: https://github.com/kubernetes-sigs/controller-runtime/blob/ab6131a999ca9e6ff5bf83dba70dc7751751135f/pkg/client/split.go#L45-L52

I don't want to use `CacheReader` and I also can't use unstructured Object.

Is there a way to make sure `client.Get()` to get the realtime result? Maybe wait for cache to sync? I don't know how.

My code is something like: https://github.com/operator-framework/operator-sdk/blob/d6903be02d4e8541e777b25af0498fe31e2e41e8/internal/pkg/scaffold/controller_kind.go#L213-L219

**Comment by joelanford** [comment]
@chenzhiwei If absolutely necessary, you can use the `client.Reader` returned by [`Manager.GetAPIReader()`](https://github.com/kubernetes-sigs/controller-runtime/blob/ab6131a999ca9e6ff5bf83dba70dc7751751135f/pkg/manager/manager.go#L84-L87) to hit the API server directly.

Could you explain a little bit more about your use case though? There might be a better way to structure your watches and reconcile method that allows you to do what you want while still leveraging the caching benefits of the split client.

Are you fetching the same object that you just updated the status of?

**Comment by chenzhiwei** [comment]
@joelanford Thank you for your reply, my use case is:

Create/Update a CRD resource will trigger a Kubernetes Job, but there is only one Job can be running at a time.

Create/Update the CRD resource and the Job status change will both trigger a Reconcile action.

I can't find a way to distinguish the Reconcile is triggered by CRD resource or Kubernetes Job.

So I need to record the Job name in the CRD resource status to avoid multiple Jobs running at one time.

My logic is: Create CRD resource, trigger a Job and set Job name to CRD resource status, next reconcile happen, then get the Job name from CRD resource status, then consider creating or waiting the Job.

**Comment by joelanford** [comment]
> I can't find a way to distinguish the Reconcile is triggered by CRD resource or Kubernetes Job.

It's generally considered a good practice to implement your `Reconcile` method such that it doesn't need to know what event triggered it. The `Reconciler` interface was specifically designed to encourage this.

> So I need to record the Job name in the CRD resource status to avoid multiple Jobs running at one time.

Another good practice is to avoid reading status fields to reconstruct state since they may be incorrect or out-of-date. In your case, consider the possibility that you trigger the `Job` successfully, but then a failure occurs when you try to update the status. On your next reconcile, you might create another `Job` since the job name is not set in the CR status.

> My logic is: Create CRD resource, trigger a Job and set Job name to CRD resource status, next reconcile happen, then get the Job name from CRD resource status, then consider creating or waiting the Job.

A better way to handle that would be to make the `Job` name (or a label value) deterministic based on the contents of the CR metadata and/or spec so that you could fetch it directly. For example, can you name the `Job` the same as the CR? If so, you wouldn't need to store the name in the CR status because you would always know it and be able to fetch the `Job` or create it if it doesn't exit.

In your case, what happens when subsequent CR updates come in when a previous `Job` is still running? Do you need to somehow queue up jobs for each CR change? Or is it okay to skip some CR updates and run a `Job` for just the most recent CR?

**Comment by chenzhiwei** [comment]
Actually I record CR spec hash and Job name to the CR status, we need both of them to handle the cases.

If the Job is running and there is another change to the CR, then the jobs will be queued and execute later.

If the Job name is same as CR, then the second update to the CR will not create the Job.

If the Job name is the CR Spec hash, then revert the CR change will not create the Job(CR hash is aaaa, then bbbb, then aaaa).

**Comment by DirectXMan12** [comment]
So, to be clear, you want to run a new job every time the CR spec changes?  That's not really how Kubernetes works (although I'm a bit fuzzy on what the exact logic is here that you want).

**Comment by chenzhiwei** [comment]
Yes, the logic in my project is weird, but I still need to implement.

Thank you all, I have another way to implement this similar logic.

**Comment by vie-serendipity** [comment]
> Are you fetching the same object that you just updated the status of?

@joelanford Are there any best practices for this situation besides using GetAPIReader?
