### ISSUE TITLE
Add nil check when applying variadic client options

### ISSUE THREAD

**Issue by rajathagasthya** [kubernetes-sigs/controller-runtime#806]
All of the `Create`, `List`, `Update` and `Delete` client methods are variadic in that it takes any number of options. For example:

```
Create(ctx context.Context, obj runtime.Object, opts ...client.CreateOption) error
```

It's too easy to pass `nil` as the last argument for these methods and then it blows up with a NPE in `ApplyOptions` method. Example: https://github.com/kubernetes-sigs/controller-runtime/blob/19e72eb88faf07f1ab7f3dd7f951bc6ae85c8d9c/pkg/client/options.go#L141

There needs to be a nil check when options are applied.

**Comment by boddumanohar** [comment]
@rajathagasthya its not possible to pass nil as a last argument to variadic function

```
package main

import (
	"fmt"
)

func printStrings(s ...string) {
	for _, s := range s {
		fmt.Println(s)
	}
}

func main() {
	printStrings("alice", "bob", nil)
}
```
https://play.golang.org/p/8iOacL4kOvX

this example will throw an error.
```
./prog.go:14:24: cannot use nil as type string in argument to printStrings
```

**Comment by rajathagasthya** [comment]
@boddumanohar `CreateOption` (and its variants) are interfaces, so it's possible to pass `nil` here.

**Comment by boddumanohar** [comment]
created a PR for this.

**Comment by alvaroaleman** [comment]
Repeating my comment from the PR in #813 , IMHO we shouldn't be doing this:

> /hold
Actually stop, I don't think we should be doing this, because methods of a nullpointer are still callable and we have a couple of examples where this works without issue, e.G. `MatchingLabels`, `HasLabels`, `MatchingFields`. Those examples here are a no-op if nil, but there could be examples out there where this is not the case. With this change, we silently stop applying them which is surprising at best.
>
> IMHO a method that does not explicitly state that it may be called with nil args can expect the caller to make sure that this doesn't happen.

**Comment by alvaroaleman** [comment]
@rajathagasthya  WDYT, does that make sense?

**Comment by rajathagasthya** [comment]
Discussed in #813. Closing based on preference not to add this check.
