### ISSUE TITLE
Webhook marker allows handler path to be changed, but a deterministic handler is always registered

### ISSUE THREAD

**Issue by rajathagasthya** [kubernetes-sigs/controller-runtime#868]
Webhook marker like the one below lets us change `path` where webhook is served. This creates the appropriate `Mutating|ValidatingWebhookConfiguration` manifest referencing this `path`.
```
// +kubebuilder:webhook:verbs=create;update,path=/validate-batch-tutorial-kubebuilder-io-v1-cronjob,mutating=false,failurePolicy=fail,groups=batch.tutorial.kubebuilder.io,resources=cronjobs,versions=v1,name=vcronjob.kb.io
```

But webhook builder always registers the same path based on GVK: https://github.com/kubernetes-sigs/controller-runtime/blob/29e923ac474ca94c021a6f8b0239a319d8b05221/pkg/builder/webhook.go#L158-L166

This is confusing when the user thinks they can customize the handler path, but it's actually ignored and worse, the generated webhook manifest doesn't work because path is incorrect. 

If we are letting users change the path through the marker, perhaps it's better to add an option to webhook builder to configure handler path as well? Or, if the path is not supposed to be changed in the marker, we should say that in docs.

**Comment by alenkacz** [comment]
maybe this bug should rather be in kubebuilder project? Since it could be solved on multiple places and might also need update in documentation?

Anyway - I took a look at it. One possible solution would be to allow overriding path inside the builder here https://github.com/kubernetes-sigs/controller-runtime/blob/dc8357113a904bf02721efcde5d92937be39031c/pkg/builder/webhook.go#L38 and use that instead of generating one if provided. If we go that way, we would also have to update docs here https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html

WDYT?

**Comment by rajathagasthya** [comment]
@alenkacz Yeah, we could provide an option in webhook builder to set path and then update docs to say "path in webhook build must match path in webhook marker" or something to that effect.

We probably also need some kind of validation if we let users set their own path.

**Comment by ryanzhang-oss** [comment]
FYI,   https://github.com/kubernetes-sigs/kubebuilder/issues/1436

**Comment by ryanzhang-oss** [comment]
> maybe this bug should rather be in kubebuilder project

https://github.com/kubernetes-sigs/kubebuilder/issues/1436

**Comment by vincepri** [comment]
/kind design

We need to think more about possible solutions

**Comment by ryanzhang-oss** [comment]
I am not familiar with the process here, what does "/help" mean? It seems that this is a pretty straightforward bug to fix.

**Comment by alexeldeib** [comment]
"/help" (adding the help-wanted label) is usually a good signal for issues to pick up 🙂 https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md#overview

However @alenkacz self-assigned, maybe she is still working on this? We did just discuss it recently. 

FWIW I think adding to the builder seems reasonable. I think @DirectXMan12 mentioned some caveats with this, but i'm not seeing them on the controller-runtime side? Was it something to do with the kubebuilder side of templating things?

**Comment by DirectXMan12** [comment]
> "path in webhook build must match path in webhook marker"

seems reasonable.  Might have to be path prefix.

My concern was mainly that we don't want to tie those two together.  Allowing you to customize the path (optionally) seems fine.

**Comment by devigned** [comment]
I was thinking about taking a look at this issue if it's not being actively worked on. Thoughts?

**Comment by DirectXMan12** [comment]
go ahead :-)

**Comment by damsien** [comment]
Hello, I am reopening this issue because the solution has not been implemented. I think that there is some users who wants to have a way to configure their webhooks using a custom path.

/reopen
/remove-lifecycle rotten

The following [PR](https://github.com/kubernetes-sigs/controller-runtime/pull/2998) implements this functionality.
